/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 06:05:21 GMT 2026
 */

package com.fasterxml.jackson.annotation;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.annotation.JsonIncludeProperties;
import com.fasterxml.jackson.annotation.OptBoolean;
import java.util.LinkedHashSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class JsonIncludeProperties_ESTest extends JsonIncludeProperties_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      OptBoolean optBoolean0 = OptBoolean.FALSE;
      String[] stringArray0 = new String[0];
      JsonIncludeProperties jsonIncludeProperties0 = mock(JsonIncludeProperties.class, CALLS_REAL_METHODS);
      doReturn(optBoolean0).when(jsonIncludeProperties0).order();
      doReturn(stringArray0).when(jsonIncludeProperties0).value();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = JsonIncludeProperties.Value.from(jsonIncludeProperties0);
      assertFalse(jsonIncludeProperties_Value0.getOrdered());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JsonIncludeProperties jsonIncludeProperties0 = mock(JsonIncludeProperties.class, CALLS_REAL_METHODS);
      doReturn((OptBoolean) null).when(jsonIncludeProperties0).order();
      doReturn((String[]) null).when(jsonIncludeProperties0).value();
      // Undeclared exception!
      try { 
        JsonIncludeProperties.Value.from(jsonIncludeProperties0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.annotation.JsonIncludeProperties$Value", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = JsonIncludeProperties.Value.from((JsonIncludeProperties) null);
      boolean boolean0 = jsonIncludeProperties_Value1.equals(jsonIncludeProperties_Value0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      Boolean boolean1 = Boolean.TRUE;
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = new JsonIncludeProperties.Value(linkedHashSet0, boolean1);
      boolean boolean2 = jsonIncludeProperties_Value1.equals(jsonIncludeProperties_Value0);
      assertFalse(boolean2);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      boolean boolean1 = jsonIncludeProperties_Value1.equals(jsonIncludeProperties_Value0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = Boolean.valueOf(true);
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      boolean boolean1 = jsonIncludeProperties_Value0.equals((Object) null);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = JsonIncludeProperties.Value.ALL;
      boolean boolean0 = jsonIncludeProperties_Value0.equals(jsonIncludeProperties_Value0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      Object object0 = new Object();
      boolean boolean1 = jsonIncludeProperties_Value0.equals(object0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = JsonIncludeProperties.Value.all();
      boolean boolean0 = linkedHashSet0.remove(jsonIncludeProperties_Value0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      boolean boolean1 = linkedHashSet0.remove(jsonIncludeProperties_Value0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = jsonIncludeProperties_Value0.withOverrides(jsonIncludeProperties_Value0);
      assertNotSame(jsonIncludeProperties_Value1, jsonIncludeProperties_Value0);
      assertTrue(jsonIncludeProperties_Value1.equals((Object)jsonIncludeProperties_Value0));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("$h]54GG#Ke5AZNb`7r");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      OptBoolean optBoolean0 = OptBoolean.DEFAULT;
      String[] stringArray0 = new String[1];
      JsonIncludeProperties jsonIncludeProperties0 = mock(JsonIncludeProperties.class, CALLS_REAL_METHODS);
      doReturn(optBoolean0).when(jsonIncludeProperties0).order();
      doReturn(stringArray0).when(jsonIncludeProperties0).value();
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = JsonIncludeProperties.Value.from(jsonIncludeProperties0);
      JsonIncludeProperties.Value jsonIncludeProperties_Value2 = jsonIncludeProperties_Value1.withOverrides(jsonIncludeProperties_Value0);
      assertFalse(jsonIncludeProperties_Value2.equals((Object)jsonIncludeProperties_Value0));
      assertNotSame(jsonIncludeProperties_Value2, jsonIncludeProperties_Value0);
      assertFalse(jsonIncludeProperties_Value2.equals((Object)jsonIncludeProperties_Value1));
      assertNotSame(jsonIncludeProperties_Value2, jsonIncludeProperties_Value1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      linkedHashSet0.add("U 6?8|");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = jsonIncludeProperties_Value0.withOverrides(jsonIncludeProperties_Value0);
      assertNotSame(jsonIncludeProperties_Value1, jsonIncludeProperties_Value0);
      assertTrue(jsonIncludeProperties_Value1.equals((Object)jsonIncludeProperties_Value0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = JsonIncludeProperties.Value.from((JsonIncludeProperties) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value2 = jsonIncludeProperties_Value1.withOverrides(jsonIncludeProperties_Value0);
      assertSame(jsonIncludeProperties_Value2, jsonIncludeProperties_Value0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = JsonIncludeProperties.Value.from((JsonIncludeProperties) null);
      JsonIncludeProperties.Value jsonIncludeProperties_Value2 = jsonIncludeProperties_Value0.withOverrides(jsonIncludeProperties_Value1);
      assertFalse(jsonIncludeProperties_Value2.equals((Object)jsonIncludeProperties_Value1));
      assertSame(jsonIncludeProperties_Value2, jsonIncludeProperties_Value0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = Boolean.valueOf(true);
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      JsonIncludeProperties.Value jsonIncludeProperties_Value1 = jsonIncludeProperties_Value0.withOverrides((JsonIncludeProperties.Value) null);
      assertSame(jsonIncludeProperties_Value0, jsonIncludeProperties_Value1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, (Boolean) null);
      String string0 = jsonIncludeProperties_Value0.toString();
      assertEquals("JsonIncludeProperties.Value(included=[],ordered=null)", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      Boolean boolean1 = jsonIncludeProperties_Value0.getOrdered();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("j:w.BxrN!bO}");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      Class<JsonIncludeProperties> class0 = jsonIncludeProperties_Value0.valueFor();
      assertFalse(class0.isEnum());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Boolean boolean0 = new Boolean("TRUE");
      JsonIncludeProperties.Value jsonIncludeProperties_Value0 = new JsonIncludeProperties.Value(linkedHashSet0, boolean0);
      boolean boolean1 = linkedHashSet0.contains(jsonIncludeProperties_Value0);
      assertFalse(boolean1);
  }
}
