/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 14:42:31 GMT 2026
 */

package org.apache.commons.math4.legacy.stat.descriptive;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.legacy.stat.descriptive.moment.SemiVariance;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class AbstractUnivariateStatistic_ESTest extends AbstractUnivariateStatistic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[7];
      double double0 = semiVariance0.evaluate(doubleArray0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[1];
      try { 
        semiVariance0.setData(doubleArray0, 21, 21);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // subarray ends after array end
         //
         verifyException("org.apache.commons.math4.legacy.stat.descriptive.AbstractUnivariateStatistic", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[0];
      semiVariance0.setData(doubleArray0, 0, 0);
      assertTrue(semiVariance0.isBiasCorrected());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[0];
      try { 
        semiVariance0.setData(doubleArray0, (-31), (-31));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // start position (-31)
         //
         verifyException("org.apache.commons.math4.legacy.stat.descriptive.AbstractUnivariateStatistic", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      // Undeclared exception!
      try { 
        semiVariance0.setData((double[]) null, 0, 6102);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // input array
         //
         verifyException("org.apache.commons.math4.legacy.stat.descriptive.AbstractUnivariateStatistic", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[2];
      try { 
        semiVariance0.setData(doubleArray0, 0, (-707));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // length (-707)
         //
         verifyException("org.apache.commons.math4.legacy.stat.descriptive.AbstractUnivariateStatistic", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = semiVariance0.getData();
      assertNull(doubleArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      semiVariance0.setData((double[]) null);
      assertTrue(semiVariance0.isBiasCorrected());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      double[] doubleArray0 = new double[0];
      semiVariance0.setData(doubleArray0);
      double[] doubleArray1 = semiVariance0.getData();
      assertNotSame(doubleArray1, doubleArray0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      SemiVariance semiVariance0 = new SemiVariance();
      // Undeclared exception!
      try { 
        semiVariance0.evaluate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // input array
         //
         verifyException("org.apache.commons.math4.legacy.core.MathArrays", e);
      }
  }
}
