/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 23:35:56 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.jsoup.internal.QuietAppendable;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.Printer;
import org.jsoup.nodes.TextNode;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Printer_ESTest extends Printer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/2000/svg", "http://www.w3.org/XML/1998/namespace");
      MockFileWriter mockFileWriter0 = new MockFileWriter("http://www.w3.org/1998/Math/MathML");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Printer printer0 = Printer.printerFor(document0, quietAppendable0);
      assertNotNull(printer0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/2000/svg", "http://www.w3.org/XML/1998/namespace");
      MockFileWriter mockFileWriter0 = new MockFileWriter("http://www.w3.org/1998/Math/MathML");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Printer.Outline printer_Outline0 = new Printer.Outline(document0, quietAppendable0, document_OutputSettings0);
      document0.appendText("http://www.w3.org/XML/1998/namespace");
      Element element0 = document0.traverse(printer_Outline0);
      assertSame(document0, element0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      CDataNode cDataNode1 = cDataNode0.clone();
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(stringBuilder0);
      Printer.Outline printer_Outline0 = new Printer.Outline(cDataNode1, quietAppendable0, (Document.OutputSettings) null);
      boolean boolean0 = printer_Outline0.shouldIndent(cDataNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/2000/svg", "http://www.w3.org/XML/1998/namespace");
      MockFileWriter mockFileWriter0 = new MockFileWriter("http://www.w3.org/1998/Math/MathML");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Printer.Outline printer_Outline0 = new Printer.Outline(document0, quietAppendable0, document_OutputSettings0);
      printer_Outline0.preserveWhitespace = true;
      printer_Outline0.addTail(document0, 1643);
      assertEquals("", document0.id());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("S*NpiP", "S*NpiP");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Document.OutputSettings document_OutputSettings1 = document_OutputSettings0.outline(true);
      document0.outputSettings(document_OutputSettings1);
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body>S*NpiP</body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("&>kY=yo1");
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "&>kY=yo1");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(stringBuilder0);
      Printer.Outline printer_Outline0 = new Printer.Outline(cDataNode0, quietAppendable0, (Document.OutputSettings) null);
      // Undeclared exception!
      try { 
        printer_Outline0.addText(cDataNode0, 1024, 8);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.Entities", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/2000/svg", "http://www.w3.org/XML/1998/namespace");
      Document document1 = (Document)document0.appendText("http://www.w3.org/XML/1998/namespace");
      document0.appendText("             ");
      CDataNode cDataNode0 = new CDataNode("http://www.w3.org/XML/1998/namespace");
      CDataNode cDataNode1 = new CDataNode("");
      Node[] nodeArray0 = new Node[3];
      nodeArray0[0] = (Node) cDataNode0;
      nodeArray0[1] = (Node) document0;
      nodeArray0[2] = (Node) cDataNode1;
      document0.addChildren(nodeArray0);
      document1.before(".A4qu.4yCsmU>Y");
      boolean boolean0 = Printer.Pretty.hasNonTextNodes(document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded(" />");
      MockFileWriter mockFileWriter0 = new MockFileWriter(" />");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Printer.Pretty printer_Pretty0 = (Printer.Pretty)Printer.printerFor(textNode0, quietAppendable0);
      Document document0 = new Document(" />", " />");
      document0.reparentChild(textNode0);
      document0.head();
      printer_Pretty0.addText(textNode0, (-1), (-1));
      assertTrue(textNode0.hasParent());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = Document.createShell("b");
      document0.prependElement("b");
      document0.prependElement("b");
      document0.prependElement("b");
      document0.prependElement("b");
      document0.prependElement("b");
      String string0 = document0.toString();
      assertEquals("<b></b><b></b><b></b><b></b><b></b>\n<html>\n <head></head>\n <body></body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded(" />");
      MockFileWriter mockFileWriter0 = new MockFileWriter(" />");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Printer.Pretty printer_Pretty0 = (Printer.Pretty)Printer.printerFor(textNode0, quietAppendable0);
      Document document0 = new Document(" />", " />");
      Element element0 = document0.body();
      // Undeclared exception!
      try { 
        printer_Pretty0.addHead(element0, (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // width must be >= 0
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = Document.createShell("br");
      document0.tagName("br", "br");
      document0.appendText("br");
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body></body>\n</html>\nbr", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = Document.createShell("br");
      Comment comment0 = new Comment("br");
      document0.appendChild(comment0);
      document0.appendText("br");
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body></body>\n</html>\n<!--br-->\nbr", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextNode textNode0 = TextNode.createFromEncoded("vSq8d/x nu<U@frER");
      MockFileWriter mockFileWriter0 = new MockFileWriter("vSq8d/x nu<U@frER");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(mockFileWriter0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Printer.Pretty printer_Pretty0 = new Printer.Pretty(textNode0, quietAppendable0, document_OutputSettings0);
      CDataNode cDataNode0 = new CDataNode("");
      Node node0 = cDataNode0.traverse(printer_Pretty0);
      assertSame(node0, cDataNode0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Document document0 = Document.createShell("br");
      document0.append("br");
      document0.appendText("br");
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body></body>\n</html>\nbrbr", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Document document0 = Parser.parse("<b></b><b></b>\n<html>\n <head></head>\n <body></body>\n</html>\nb", "");
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body>\n  <b></b><b></b> b\n </body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("S*NpiP", "S*NpiP");
      document0.prependText("S*NpiP");
      String string0 = document0.toString();
      assertEquals("S*NpiP\n<html>\n <head></head>\n <body>S*NpiP</body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Parser.parse(";LsK[I<HGG0N`Y>jC@@", "6lKNy");
      String string0 = document0.toString();
      assertEquals("<html>\n <head></head>\n <body>\n  ;LsK[I<hgg0n`y>jC@@</hgg0n`y>\n </body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Document.createShell("\"");
      Tag.Data = 2922;
      document0.title("\"");
      String string0 = document0.toString();
      assertEquals("<html>\n <head>\n  <title>\"</title>\n </head>\n <body></body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Document document0 = Document.createShell("\"");
      Tag.PreserveWhitespace = 3;
      String string0 = document0.toString();
      assertEquals("<html><head></head><body></body></html>", string0);
  }
}
