/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 23:28:08 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.parser.HtmlTreeBuilder;
import org.jsoup.parser.Parser;
import org.jsoup.parser.StreamParser;
import org.jsoup.select.Evaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class StreamParser_ESTest extends StreamParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parse("http://www.w3.org/2000/svg", "http://www.w3.org/1998/math/mathml");
      List<Node> list0 = streamParser1.completeFragment();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HtmlTreeBuilder htmlTreeBuilder0 = new HtmlTreeBuilder();
      Parser parser0 = new Parser(htmlTreeBuilder0);
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parse("", "[vo4l)SZUv");
      Document document0 = streamParser1.complete();
      assertEquals("[vo4l)SZUv", document0.location());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser.ElementIterator streamParser_ElementIterator0 = streamParser0.new ElementIterator();
      streamParser_ElementIterator0.tail((Node) null, (-8));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser.ElementIterator streamParser_ElementIterator0 = streamParser0.new ElementIterator();
      // Undeclared exception!
      try { 
        streamParser_ElementIterator0.remove();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.StreamParser$ElementIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser.ElementIterator streamParser_ElementIterator0 = streamParser0.new ElementIterator();
      Document document0 = parser0.parseInput("", "");
      streamParser_ElementIterator0.tail(document0, 644);
      Element element0 = streamParser_ElementIterator0.next();
      assertTrue(element0.isBlock());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parse("http://www.w3.org/XML/1998/namespace", "http://www.w3.org/1998/Math/MathML");
      StreamParser.ElementIterator streamParser_ElementIterator0 = streamParser1.new ElementIterator();
      // Undeclared exception!
      try { 
        streamParser_ElementIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.StreamParser$ElementIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      streamParser0.parse("http://www.w3.org/1999/xhtml", "*oF(");
      Pattern pattern0 = Pattern.compile("");
      Evaluator.MatchesWholeText evaluator_MatchesWholeText0 = new Evaluator.MatchesWholeText(pattern0);
      Document document0 = (Document)streamParser0.selectFirst((Evaluator) evaluator_MatchesWholeText0);
      assertEquals("*oF(", document0.location());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      streamParser0.parse("http://www.w3.org/2000/svg", "");
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("http://www.w3.org/XML/1998/namespace");
      Element element0 = streamParser0.selectFirst((Evaluator) evaluator_ContainsData0);
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parseFragment("http://www.w3.org/XML/1998/namespace", (Element) null, "http://www.w3.org/2000/svg");
      assertSame(streamParser1, streamParser0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.expectNext("http://www.w3.org/XML/1998/namespace");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query 'http://www.w3.org/XML/1998/namespace': unexpected token at '//www.w3.org/XML/1998/namespace'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.expectFirst("org.jsoup.parser.StreamParser");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must run parse() before calling.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      StreamParser streamParser1 = streamParser0.parse("time", "http://www.w3.org/2000/svg");
      streamParser1.selectNext((Evaluator) evaluator_IsLastChild0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      Iterator<Element> iterator0 = streamParser0.iterator();
      assertNotNull(iterator0);
  }
}
