package org.apache.commons.codec.binary;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import java.util.Random;

import org.junit.jupiter.api.Test;

/**
 * Verifies that Base16 encoding followed by decoding is a round-trip:
 * decoding the encoded form of any byte array must reproduce the original bytes.
 */
public class Base16Test_testEncodeDecodeRandom {

    /** Number of randomized round-trip iterations to run. */
    private static final int ITERATIONS = 4;

    /** Upper bound (exclusive, before the +1 offset) for a randomly chosen array length. */
    private static final int MAX_RANDOM_LENGTH = 10000;

    private final Random random = new Random();

    /**
     * Encodes and then decodes several large, randomly generated byte arrays and
     * asserts that the decoded result equals the original input each time.
     */
    @Test
    void testEncodeDecodeRandom() {
        for (int iteration = 0; iteration < ITERATIONS; iteration++) {
            // Random length between 1 and MAX_RANDOM_LENGTH (inclusive).
            final int length = random.nextInt(MAX_RANDOM_LENGTH) + 1;
            final byte[] original = new byte[length];
            random.nextBytes(original);

            final byte[] encoded = new Base16().encode(original);
            final byte[] decoded = new Base16().decode(encoded);

            assertArrayEquals(original, decoded);
        }
    }
}
