/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 04:33:54 GMT 2026
 */

package org.apache.commons.collections4.bag;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.EnumSet;
import java.util.Locale;
import org.apache.commons.collections4.SortedBag;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.bag.CollectionSortedBag;
import org.apache.commons.collections4.bag.TreeBag;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CollectionSortedBag_ESTest extends CollectionSortedBag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      TreeBag<Locale.FilteringMode> treeBag1 = new TreeBag<Locale.FilteringMode>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      treeBag1.add(locale_FilteringMode0);
      CollectionSortedBag<Locale.FilteringMode> collectionSortedBag0 = new CollectionSortedBag<Locale.FilteringMode>(treeBag1);
      boolean boolean0 = collectionSortedBag0.retainAll(treeBag0);
      assertFalse(collectionSortedBag0.contains(locale_FilteringMode0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      Integer integer0 = new Integer(0);
      treeBag0.add(integer0);
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      boolean boolean0 = collectionSortedBag0.retainAll(treeBag0);
      assertEquals(1, treeBag0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TreeBag<Locale.Category> treeBag0 = new TreeBag<Locale.Category>();
      TreeBag<Object> treeBag1 = new TreeBag<Object>((Collection<?>) treeBag0);
      CollectionSortedBag<Object> collectionSortedBag0 = new CollectionSortedBag<Object>(treeBag1);
      // Undeclared exception!
      try { 
        collectionSortedBag0.retainAll((Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.bag.AbstractMapBag", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      TreeBag<Integer> treeBag1 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag1);
      Integer integer0 = new Integer(2170);
      treeBag0.add(integer0);
      boolean boolean0 = collectionSortedBag0.removeAll(treeBag0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      Integer integer0 = new Integer((-1040));
      treeBag0.add(integer0);
      collectionSortedBag0.addAll(treeBag0);
      TreeBag<Object> treeBag1 = new TreeBag<Object>((Iterable<?>) treeBag0);
      boolean boolean0 = collectionSortedBag0.removeAll(treeBag1);
      assertFalse(collectionSortedBag0.contains((-1040)));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      boolean boolean0 = collectionSortedBag0.removeAll((Collection<?>) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      Locale.FilteringMode locale_FilteringMode1 = Locale.FilteringMode.EXTENDED_FILTERING;
      EnumSet<Locale.FilteringMode> enumSet0 = EnumSet.of(locale_FilteringMode0, locale_FilteringMode1, locale_FilteringMode1, locale_FilteringMode1, locale_FilteringMode1);
      TreeBag<Locale.FilteringMode> treeBag0 = new TreeBag<Locale.FilteringMode>((Iterable<? extends Locale.FilteringMode>) enumSet0);
      CollectionSortedBag<Locale.FilteringMode> collectionSortedBag0 = new CollectionSortedBag<Locale.FilteringMode>(treeBag0);
      boolean boolean0 = collectionSortedBag0.addAll(enumSet0);
      assertEquals(4, treeBag0.size());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      // Undeclared exception!
      try { 
        collectionSortedBag0.remove((Object) treeBag0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionSortedBag.collectionSortedBag((SortedBag<Transformer<Integer, Integer>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      boolean boolean0 = collectionSortedBag0.containsAll(treeBag0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TreeBag<Integer> treeBag0 = new TreeBag<Integer>();
      CollectionSortedBag<Integer> collectionSortedBag0 = new CollectionSortedBag<Integer>(treeBag0);
      Integer integer0 = new Integer((-1040));
      boolean boolean0 = collectionSortedBag0.add(integer0);
      assertEquals(1, treeBag0.size());
      assertTrue(boolean0);
  }
}
