/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 04:35:29 GMT 2026
 */

package org.apache.commons.collections4.bag;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Set;
import java.util.Stack;
import org.apache.commons.collections4.Bag;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.SortedBag;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.bag.CollectionSortedBag;
import org.apache.commons.collections4.bag.PredicatedSortedBag;
import org.apache.commons.collections4.bag.SynchronizedSortedBag;
import org.apache.commons.collections4.bag.TransformedBag;
import org.apache.commons.collections4.bag.TransformedSortedBag;
import org.apache.commons.collections4.bag.TreeBag;
import org.apache.commons.collections4.functors.AllPredicate;
import org.apache.commons.collections4.functors.ConstantTransformer;
import org.apache.commons.collections4.functors.InvokerTransformer;
import org.apache.commons.collections4.functors.NonePredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class TransformedBag_ESTest extends TransformedBag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TreeBag<Predicate<Object>> treeBag0 = new TreeBag<Predicate<Object>>();
      Transformer<Object, Predicate<Object>> transformer0 = ConstantTransformer.nullTransformer();
      TransformedSortedBag<Predicate<Object>> transformedSortedBag0 = TransformedSortedBag.transformingSortedBag((SortedBag<Predicate<Object>>) treeBag0, (Transformer<? super Predicate<Object>, ? extends Predicate<Object>>) transformer0);
      Predicate<Object> predicate0 = AllPredicate.allPredicate((Collection<? extends Predicate<? super Object>>) transformedSortedBag0);
      PredicatedSortedBag<Predicate<Object>> predicatedSortedBag0 = new PredicatedSortedBag<Predicate<Object>>(transformedSortedBag0, predicate0);
      CollectionSortedBag<Predicate<Object>> collectionSortedBag0 = new CollectionSortedBag<Predicate<Object>>(predicatedSortedBag0);
      TransformedSortedBag<Predicate<Object>> transformedSortedBag1 = TransformedSortedBag.transformingSortedBag((SortedBag<Predicate<Object>>) collectionSortedBag0, (Transformer<? super Predicate<Object>, ? extends Predicate<Object>>) transformer0);
      boolean boolean0 = transformedSortedBag1.equals(transformedSortedBag0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TreeBag<Predicate<Object>> treeBag0 = new TreeBag<Predicate<Object>>();
      Transformer<Object, Predicate<Object>> transformer0 = ConstantTransformer.nullTransformer();
      TransformedSortedBag<Predicate<Object>> transformedSortedBag0 = TransformedSortedBag.transformingSortedBag((SortedBag<Predicate<Object>>) treeBag0, (Transformer<? super Predicate<Object>, ? extends Predicate<Object>>) transformer0);
      Integer integer0 = new Integer((-828));
      boolean boolean0 = transformedSortedBag0.equals(integer0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(1564, 1564, 0, 0).when(comparator0).compare(any() , any());
      TreeBag<Predicate<Integer>> treeBag0 = new TreeBag<Predicate<Integer>>(comparator0);
      Predicate<Integer> predicate0 = NonePredicate.nonePredicate((Collection<? extends Predicate<? super Integer>>) treeBag0);
      treeBag0.add(predicate0);
      Transformer<Object, Predicate<Integer>> transformer0 = InvokerTransformer.invokerTransformer("");
      TransformedBag.transformedBag((Bag<Predicate<Integer>>) treeBag0, (Transformer<? super Predicate<Integer>, ? extends Predicate<Integer>>) transformer0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeBag<Predicate<Integer>> treeBag0 = new TreeBag<Predicate<Integer>>(comparator0);
      Transformer<Object, Predicate<Integer>> transformer0 = InvokerTransformer.invokerTransformer("");
      Bag<Predicate<Integer>> bag0 = TransformedBag.transformedBag((Bag<Predicate<Integer>>) treeBag0, (Transformer<? super Predicate<Integer>, ? extends Predicate<Integer>>) transformer0);
      assertEquals(0, bag0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeBag<Locale.FilteringMode> treeBag0 = new TreeBag<Locale.FilteringMode>(comparator0);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 2);
      InvokerTransformer<Object, Locale.FilteringMode> invokerTransformer0 = new InvokerTransformer<Object, Locale.FilteringMode>("", classArray0, classArray0);
      TransformedBag<Locale.FilteringMode> transformedBag0 = new TransformedBag<Locale.FilteringMode>(treeBag0, invokerTransformer0);
      boolean boolean0 = transformedBag0.remove((Object) transformedBag0, 1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Stack<Locale.FilteringMode> stack0 = new Stack<Locale.FilteringMode>();
      TreeBag<Object> treeBag0 = new TreeBag<Object>((Collection<?>) stack0);
      CollectionSortedBag<Object> collectionSortedBag0 = new CollectionSortedBag<Object>(treeBag0);
      SynchronizedSortedBag<Object> synchronizedSortedBag0 = new SynchronizedSortedBag<Object>(collectionSortedBag0);
      Transformer<Object, Object> transformer0 = ConstantTransformer.nullTransformer();
      TransformedSortedBag<Object> transformedSortedBag0 = new TransformedSortedBag<Object>(synchronizedSortedBag0, transformer0);
      boolean boolean0 = transformedSortedBag0.add((Object) synchronizedSortedBag0, (-27));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedHashSet<Integer> linkedHashSet0 = new LinkedHashSet<Integer>();
      TreeBag<Object> treeBag0 = new TreeBag<Object>((Collection<?>) linkedHashSet0);
      Integer integer0 = new Integer((-798));
      ConstantTransformer<Object, Integer> constantTransformer0 = new ConstantTransformer<Object, Integer>(integer0);
      TransformedSortedBag<Object> transformedSortedBag0 = new TransformedSortedBag<Object>(treeBag0, constantTransformer0);
      transformedSortedBag0.hashCode();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Transformer<Object, Integer> transformer0 = InvokerTransformer.invokerTransformer("org.apache.commons.collections4.bag.TransformedBag");
      // Undeclared exception!
      try { 
        TransformedBag.transformingBag((Bag<Integer>) null, (Transformer<? super Integer, ? extends Integer>) transformer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeBag<Locale.FilteringMode> treeBag0 = new TreeBag<Locale.FilteringMode>(comparator0);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 2);
      InvokerTransformer<Object, Locale.FilteringMode> invokerTransformer0 = new InvokerTransformer<Object, Locale.FilteringMode>("", classArray0, classArray0);
      TransformedBag<Locale.FilteringMode> transformedBag0 = new TransformedBag<Locale.FilteringMode>(treeBag0, invokerTransformer0);
      Object object0 = new Object();
      int int0 = transformedBag0.getCount(object0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeBag<Locale.FilteringMode> treeBag0 = new TreeBag<Locale.FilteringMode>(comparator0);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 2);
      InvokerTransformer<Object, Locale.FilteringMode> invokerTransformer0 = new InvokerTransformer<Object, Locale.FilteringMode>("", classArray0, classArray0);
      TransformedBag<Locale.FilteringMode> transformedBag0 = new TransformedBag<Locale.FilteringMode>(treeBag0, invokerTransformer0);
      Set<Locale.FilteringMode> set0 = transformedBag0.uniqueSet();
      assertEquals(0, set0.size());
  }
}
