/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 15:35:45 GMT 2026
 */

package org.apache.commons.math4.legacy.linear;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.legacy.analysis.differentiation.DerivativeStructure;
import org.apache.commons.math4.legacy.analysis.function.Cosh;
import org.apache.commons.math4.legacy.core.Field;
import org.apache.commons.math4.legacy.linear.FieldMatrix;
import org.apache.commons.math4.legacy.linear.SparseFieldMatrix;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class SparseFieldMatrix_ESTest extends SparseFieldMatrix_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Cosh cosh0 = new Cosh();
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0, 0);
      DerivativeStructure derivativeStructure1 = cosh0.value(derivativeStructure0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 533, 619);
      sparseFieldMatrix0.setEntry(0, 0, derivativeStructure1);
      assertEquals(533, sparseFieldMatrix0.getRowDimension());
      assertEquals(619, sparseFieldMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 533, 619);
      sparseFieldMatrix0.multiplyEntry(402, 533, derivativeStructure0);
      assertEquals(619, sparseFieldMatrix0.getColumnDimension());
      assertEquals(533, sparseFieldMatrix0.getRowDimension());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cosh cosh0 = new Cosh();
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      DerivativeStructure derivativeStructure1 = cosh0.value(derivativeStructure0);
      DerivativeStructure derivativeStructure2 = new DerivativeStructure(2187.76565425, derivativeStructure1, 0, derivativeStructure0, 0, derivativeStructure1, 0.0, derivativeStructure0);
      Field<DerivativeStructure> field0 = derivativeStructure1.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 619, 1);
      DerivativeStructure derivativeStructure3 = cosh0.value(derivativeStructure2);
      sparseFieldMatrix0.multiplyEntry(402, 0, derivativeStructure3);
      assertEquals(1, sparseFieldMatrix0.getColumnDimension());
      assertEquals(619, sparseFieldMatrix0.getRowDimension());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 533, 619);
      sparseFieldMatrix0.addToEntry(402, 402, derivativeStructure0);
      assertEquals(619, sparseFieldMatrix0.getColumnDimension());
      assertEquals(533, sparseFieldMatrix0.getRowDimension());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Cosh cosh0 = new Cosh();
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      DerivativeStructure derivativeStructure1 = cosh0.value(derivativeStructure0);
      Field<DerivativeStructure> field0 = derivativeStructure1.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 619, 1);
      sparseFieldMatrix0.addToEntry(1, 0, derivativeStructure1);
      assertEquals(619, sparseFieldMatrix0.getRowDimension());
      assertEquals(1, sparseFieldMatrix0.getColumnDimension());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 619, 1);
      FieldMatrix<DerivativeStructure> fieldMatrix0 = sparseFieldMatrix0.copy();
      assertEquals(1, fieldMatrix0.getColumnDimension());
      assertEquals(619, fieldMatrix0.getRowDimension());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 619, 619);
      // Undeclared exception!
      try { 
        sparseFieldMatrix0.createMatrix(343, 0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // dimension (0)
         //
         verifyException("org.apache.commons.math4.legacy.linear.AbstractFieldMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0);
      assertTrue(sparseFieldMatrix0.isSquare());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DerivativeStructure derivativeStructure0 = new DerivativeStructure(0, 0);
      Field<DerivativeStructure> field0 = derivativeStructure0.getField();
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix0 = new SparseFieldMatrix<DerivativeStructure>(field0, 619, 1);
      SparseFieldMatrix<DerivativeStructure> sparseFieldMatrix1 = new SparseFieldMatrix<DerivativeStructure>((FieldMatrix<DerivativeStructure>) sparseFieldMatrix0);
      assertEquals(1, sparseFieldMatrix0.getColumnDimension());
      assertEquals(619, sparseFieldMatrix0.getRowDimension());
      assertFalse(sparseFieldMatrix0.isSquare());
  }
}
