/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 02:03:04 GMT 2026
 */

package org.threeten.extra;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Year;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.HijrahDate;
import java.time.chrono.MinguoDate;
import java.time.temporal.ChronoField;
import java.time.temporal.Temporal;
import java.time.temporal.TemporalField;
import java.time.temporal.TemporalQuery;
import java.time.temporal.UnsupportedTemporalTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.MockYear;
import org.evosuite.runtime.mock.java.time.MockYearMonth;
import org.evosuite.runtime.mock.java.time.chrono.MockHijrahDate;
import org.evosuite.runtime.mock.java.time.chrono.MockMinguoDate;
import org.junit.runner.RunWith;
import org.threeten.extra.DayOfYear;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class DayOfYear_ESTest extends DayOfYear_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void ofNegativeDayThrowsDateTimeException()  throws Throwable  {
      try {
        DayOfYear.of((-408));
        fail("Expecting exception: DateTimeException");

      } catch(DateTimeException e) {
         //
         // Invalid value for DayOfYear: -408
         //
      }
  }

  @Test(timeout = 4000)
  public void fromZoneOffsetThrowsDateTimeException()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      try {
        DayOfYear.from(zoneOffset0);
        fail("Expecting exception: DateTimeException");

      } catch(DateTimeException e) {
         //
         // Unable to obtain DayOfYear from TemporalAccessor: +18:00 of type java.time.ZoneOffset
         //
      }
  }

  @Test(timeout = 4000)
  public void equalsReturnsTrueForSameInstance()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      boolean isSameInstance = dayOfYear0.equals(dayOfYear0);
  }

  @Test(timeout = 4000)
  public void equalsReturnsFalseForDifferentType()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      Clock clock0 = MockClock.systemUTC();
      boolean isDifferentType = dayOfYear0.equals(clock0);
  }

  @Test(timeout = 4000)
  public void adjustIntoNonIsoTemporalThrowsDateTimeException()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      HijrahDate hijrahDate0 = MockHijrahDate.now((ZoneId) zoneOffset0);
      try {
        dayOfYear0.adjustInto(hijrahDate0);
        fail("Expecting exception: DateTimeException");

      } catch(DateTimeException e) {
         //
         // Adjustment only supported on ISO date-time
         //
      }
  }

  @Test(timeout = 4000)
  public void adjustIntoIsoLocalDateSucceeds()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      LocalDate localDate0 = MockLocalDate.now();
      Temporal adjusted = dayOfYear0.adjustInto(localDate0);
  }

  @Test(timeout = 4000)
  public void queryWithCustomTemporalQueryDelegatesCorrectly()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      TemporalQuery<Object> temporalQuery0 = (TemporalQuery<Object>) mock(TemporalQuery.class, new ViolatedAssumptionAnswer());
      doReturn(dayOfYear0).when(temporalQuery0).queryFrom(any(java.time.temporal.TemporalAccessor.class));
      DayOfYear dayOfYear1 = (DayOfYear)dayOfYear0.query(temporalQuery0);
  }

  @Test(timeout = 4000)
  public void isValidYearForDay366WithLeapYear()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.of(366);
      boolean isValid = dayOfYear0.isValidYear(366);
  }

  @Test(timeout = 4000)
  public void isValidYearForDay366WithNonLeapYear()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.of(366);
      boolean isValid = dayOfYear0.isValidYear((-488));
  }

  @Test(timeout = 4000)
  public void isValidYearForDayBefore366AlwaysTrue()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      boolean isValid = dayOfYear0.isValidYear((-1717));
  }

  @Test(timeout = 4000)
  public void getLongUnsupportedChronoFieldThrowsException()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      ChronoField chronoField0 = ChronoField.ALIGNED_DAY_OF_WEEK_IN_MONTH;
      try {
        dayOfYear0.getLong(chronoField0);
        fail("Expecting exception: UnsupportedTemporalTypeException");

      } catch(UnsupportedTemporalTypeException e) {
         //
         // Unsupported field: AlignedDayOfWeekInMonth
         //
      }
  }

  @Test(timeout = 4000)
  public void getLongDayOfYearFieldReturnsValue()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      ChronoField chronoField0 = ChronoField.DAY_OF_YEAR;
      long dayValue = dayOfYear0.getLong(chronoField0);
  }

  @Test(timeout = 4000)
  public void getLongNullFieldThrowsNullPointerException()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      try {
        dayOfYear0.getLong((TemporalField) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void isSupportedDayOfYearFieldReturnsTrue()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      ChronoField chronoField0 = ChronoField.DAY_OF_YEAR;
      boolean isSupported = dayOfYear0.isSupported(chronoField0);
  }

  @Test(timeout = 4000)
  public void isSupportedNullFieldReturnsFalse()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      boolean isSupported = dayOfYear0.isSupported((TemporalField) null);
  }

  @Test(timeout = 4000)
  public void fromMinguoDateExtractsDayOfYear()  throws Throwable  {
      MinguoDate minguoDate0 = MockMinguoDate.now();
      DayOfYear dayOfYear0 = DayOfYear.from(minguoDate0);
  }

  @Test(timeout = 4000)
  public void fromDayOfYearReturnsSameInstance()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      DayOfYear dayOfYear1 = DayOfYear.from(dayOfYear0);
  }

  @Test(timeout = 4000)
  public void nowWithDifferentZoneOffsetsMayDiffer()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      DayOfYear dayOfYear0 = DayOfYear.now((ZoneId) zoneOffset0);
      DayOfYear dayOfYear1 = DayOfYear.now();
      boolean isEqual = dayOfYear1.equals(dayOfYear0);
  }

  @Test(timeout = 4000)
  public void getValueReturnsCurrentDayOfYear()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      int value = dayOfYear0.getValue();
  }

  @Test(timeout = 4000)
  public void hashCodeReturnsConsistentValue()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      dayOfYear0.hashCode();
  }

  @Test(timeout = 4000)
  public void compareToSameInstanceReturnsZero()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      int comparison = dayOfYear0.compareTo(dayOfYear0);
  }

  @Test(timeout = 4000)
  public void atYearIntAndFromLocalDateRoundTrip()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      LocalDate localDate0 = dayOfYear0.atYear(1);
      DayOfYear dayOfYear1 = DayOfYear.from(localDate0);
  }

  @Test(timeout = 4000)
  public void atYearWithYearObjectReturnsLocalDate()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      Year year0 = MockYear.now();
      dayOfYear0.atYear(year0);
  }

  @Test(timeout = 4000)
  public void fromDayOfYearViaYearMonthQueryThrowsDateTimeException()  throws Throwable  {
      DayOfYear dayOfYear0 = DayOfYear.now();
      try {
        MockYearMonth.from(dayOfYear0);
        fail("Expecting exception: DateTimeException");

      } catch(DateTimeException e) {
         //
         // Unable to obtain YearMonth from TemporalAccessor: DayOfYear:45 of type org.threeten.extra.DayOfYear
         //
      }
  }
}
