/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 06:36:38 GMT 2026
 */

package org.apache.commons.collections4.bloomfilter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.collections4.bloomfilter.ArrayCountingBloomFilter;
import org.apache.commons.collections4.bloomfilter.BitMapExtractor;
import org.apache.commons.collections4.bloomfilter.BloomFilter;
import org.apache.commons.collections4.bloomfilter.CellExtractor;
import org.apache.commons.collections4.bloomfilter.EnhancedDoubleHasher;
import org.apache.commons.collections4.bloomfilter.Hasher;
import org.apache.commons.collections4.bloomfilter.IndexExtractor;
import org.apache.commons.collections4.bloomfilter.Shape;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ArrayCountingBloomFilter_ESTest extends ArrayCountingBloomFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Shape shape0 = Shape.fromKM(4, 4);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      int[] intArray0 = new int[5];
      intArray0[0] = 4;
      IndexExtractor indexExtractor0 = IndexExtractor.fromIndexArray(intArray0);
      // Undeclared exception!
      try { 
        arrayCountingBloomFilter0.remove(indexExtractor0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Filter only accepts values in the [0,4) range
         //
         verifyException("org.apache.commons.collections4.bloomfilter.ArrayCountingBloomFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(4, 4);
      Shape shape0 = Shape.fromKM(4, 1);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      // Undeclared exception!
      try { 
        arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Filter only accepts values in the [0,1) range
         //
         verifyException("org.apache.commons.collections4.bloomfilter.ArrayCountingBloomFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 247L);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      ArrayCountingBloomFilter arrayCountingBloomFilter1 = arrayCountingBloomFilter0.copy();
      boolean boolean0 = arrayCountingBloomFilter1.merge((Hasher) enhancedDoubleHasher0);
      boolean boolean1 = arrayCountingBloomFilter0.contains((BloomFilter<?>) arrayCountingBloomFilter1);
      assertTrue(arrayCountingBloomFilter0.isValid());
      assertEquals(1, arrayCountingBloomFilter1.characteristics());
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 257);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 257);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      boolean boolean0 = arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
      boolean boolean1 = arrayCountingBloomFilter0.isEmpty();
      assertFalse(boolean1 == boolean0);
      assertTrue(arrayCountingBloomFilter0.isValid());
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 257);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      boolean boolean0 = arrayCountingBloomFilter0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 247L);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      ArrayCountingBloomFilter arrayCountingBloomFilter1 = arrayCountingBloomFilter0.copy();
      arrayCountingBloomFilter1.merge((Hasher) enhancedDoubleHasher0);
      arrayCountingBloomFilter0.subtract(arrayCountingBloomFilter1);
      assertTrue(arrayCountingBloomFilter1.isValid());
      
      int int0 = arrayCountingBloomFilter0.getMaxInsert((IndexExtractor) arrayCountingBloomFilter0);
      assertFalse(arrayCountingBloomFilter0.isValid());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Shape shape0 = Shape.fromNMK(4, 4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(4, 4);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
      int int0 = arrayCountingBloomFilter0.getMaxInsert((CellExtractor) arrayCountingBloomFilter0);
      assertEquals(1, int0);
      assertTrue(arrayCountingBloomFilter0.isValid());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(4, 4);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      boolean boolean0 = arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
      boolean boolean1 = arrayCountingBloomFilter0.contains((IndexExtractor) arrayCountingBloomFilter0);
      assertTrue(arrayCountingBloomFilter0.isValid());
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 247L);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      ArrayCountingBloomFilter arrayCountingBloomFilter1 = arrayCountingBloomFilter0.copy();
      boolean boolean0 = arrayCountingBloomFilter1.merge((Hasher) enhancedDoubleHasher0);
      boolean boolean1 = arrayCountingBloomFilter0.contains((BitMapExtractor) arrayCountingBloomFilter1);
      assertTrue(arrayCountingBloomFilter0.isValid());
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 247L);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
      int int0 = arrayCountingBloomFilter0.cardinality();
      assertEquals(1, int0);
      assertTrue(arrayCountingBloomFilter0.isValid());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(4, 4);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      arrayCountingBloomFilter0.merge((Hasher) enhancedDoubleHasher0);
      int[] intArray0 = arrayCountingBloomFilter0.asIndexArray();
      assertArrayEquals(new int[] {0}, intArray0);
      assertTrue(arrayCountingBloomFilter0.isValid());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Shape shape0 = Shape.fromNM(4, 4);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      ArrayCountingBloomFilter arrayCountingBloomFilter1 = arrayCountingBloomFilter0.copy();
      EnhancedDoubleHasher enhancedDoubleHasher0 = new EnhancedDoubleHasher(0L, 4);
      arrayCountingBloomFilter1.merge((Hasher) enhancedDoubleHasher0);
      int int0 = arrayCountingBloomFilter0.getMaxInsert((CellExtractor) arrayCountingBloomFilter1);
      assertEquals(0, int0);
      assertTrue(arrayCountingBloomFilter1.isValid());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Shape shape0 = Shape.fromNM(19, 19);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      int int0 = arrayCountingBloomFilter0.getMaxCell();
      assertEquals(Integer.MAX_VALUE, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Shape shape0 = Shape.fromNM(10, 10);
      ArrayCountingBloomFilter arrayCountingBloomFilter0 = new ArrayCountingBloomFilter(shape0);
      arrayCountingBloomFilter0.clear();
      assertTrue(arrayCountingBloomFilter0.isValid());
  }
}
