package org.apache.commons.io.input;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;

import org.junit.jupiter.api.Test;
import org.junit.platform.commons.util.StringUtils;

/**
 * Tests that {@link NullInputStream#read(byte[])} (and the offset/length variant)
 * throws an {@link EOFException} once the emulated stream is exhausted, when the
 * stream is configured to throw at end-of-file.
 */
public class NullInputStreamTest_testReadByteArrayThrowAtEof {

    /** Size of the emulated stream under test. */
    private static final int STREAM_SIZE = 15;

    /** Size of the buffer the test reads into. */
    private static final int BUFFER_SIZE = 10;

    /**
     * A {@link NullInputStream} whose generated bytes encode their own absolute
     * position in the stream, so the test can verify which bytes were produced.
     */
    private static final class TestNullInputStream extends NullInputStream {

        TestNullInputStream(final int size) {
            super(size);
        }

        TestNullInputStream(final int size, final boolean markSupported, final boolean throwEofException) {
            super(size, markSupported, throwEofException);
        }

        @Override
        protected int processByte() {
            return (int) getPosition() - 1;
        }

        @Override
        protected void processBytes(final byte[] bytes, final int offset, final int length) {
            final int startPos = (int) getPosition() - length;
            for (int i = offset; i < length; i++) {
                bytes[i] = (byte) (startPos + i);
            }
        }
    }

    @Test
    void testReadByteArrayThrowAtEof() throws Exception {
        final byte[] bytes = new byte[BUFFER_SIZE];

        // A 15-byte stream that supports mark and throws EOFException at the end.
        try (NullInputStream input = new TestNullInputStream(STREAM_SIZE, true, true)) {

            // First read fills the whole buffer: bytes 0..9 of the stream.
            final int firstReadCount = input.read(bytes);
            assertEquals(BUFFER_SIZE, firstReadCount, "First read should fill the buffer");
            for (int i = 0; i < firstReadCount; i++) {
                assertEquals(i, bytes[i], "First read should yield stream bytes 0..9");
            }

            // Second read returns only the 5 bytes left in the 15-byte stream.
            final int secondReadCount = input.read(bytes);
            assertEquals(STREAM_SIZE - BUFFER_SIZE, secondReadCount, "Second read should return the remaining bytes");
            for (int i = 0; i < secondReadCount; i++) {
                assertEquals(firstReadCount + i, bytes[i], "Second read should yield stream bytes 10..14");
            }

            // Reading at end-of-file throws because throwEofException is enabled.
            final IOException eofAtEnd = assertThrows(EOFException.class, () -> input.read(bytes));
            assertTrue(StringUtils.isNotBlank(eofAtEnd.getMessage()), "EOFException should carry a message");

            // Reading again past end-of-file keeps throwing.
            final IOException eofPastEnd = assertThrows(EOFException.class, () -> input.read(bytes));
            assertTrue(StringUtils.isNotBlank(eofPastEnd.getMessage()), "Repeated read at EOF should still throw with a message");

            // Re-initialize the stream so it can be read from the start again.
            input.init();

            // Read into the buffer at an offset using the (bytes, offset, length) overload.
            final int offset = 2;
            final int length = 4;
            final int offsetReadCount = input.read(bytes, offset, length);
            assertEquals(length, offsetReadCount, "Offset read should return the requested length");
            for (int i = offset; i < length; i++) {
                assertEquals(i, bytes[i], "Offset read should yield stream bytes at their position");
            }
        }
    }
}
