/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 01:17:25 GMT 2026
 */

package org.threeten.extra.chrono;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.chrono.ChronoZonedDateTime;
import java.time.chrono.Era;
import java.time.chrono.ThaiBuddhistEra;
import java.time.format.ResolverStyle;
import java.time.format.TextStyle;
import java.time.temporal.ChronoField;
import java.time.temporal.TemporalAccessor;
import java.time.temporal.TemporalAdjuster;
import java.time.temporal.TemporalField;
import java.time.temporal.UnsupportedTemporalTypeException;
import java.time.temporal.ValueRange;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockZonedDateTime;
import org.junit.runner.RunWith;
import org.threeten.extra.chrono.JulianChronology;
import org.threeten.extra.chrono.JulianDate;
import org.threeten.extra.chrono.JulianEra;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class JulianChronology_ESTest extends JulianChronology_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      JulianDate julianDate0 = julianChronology0.dateNow((ZoneId) zoneOffset0);
      // Undeclared exception!
      try { 
        julianDate0.with((TemporalAdjuster) zoneOffset0);
        fail("Expecting exception: UnsupportedTemporalTypeException");
      
      } catch(UnsupportedTemporalTypeException e) {
         //
         // Unsupported field: OffsetSeconds
         //
         verifyException("org.threeten.extra.chrono.AbstractDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      ChronoField chronoField0 = ChronoField.YEAR;
      ValueRange valueRange0 = julianChronology0.INSTANCE.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      ChronoField chronoField0 = ChronoField.YEAR_OF_ERA;
      ValueRange valueRange0 = julianChronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      ChronoField chronoField0 = ChronoField.PROLEPTIC_MONTH;
      ValueRange valueRange0 = julianChronology0.INSTANCE.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      JulianEra julianEra0 = JulianEra.AD;
      int int0 = julianChronology0.prolepticYear(julianEra0, 652);
      assertEquals(652, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      JulianEra julianEra0 = JulianEra.BC;
      int int0 = julianChronology0.prolepticYear(julianEra0, 19);
      assertEquals((-18), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      boolean boolean0 = julianChronology0.isLeapYear((-11999988L));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      JulianDate julianDate0 = julianChronology0.INSTANCE.dateEpochDay(2L);
      assertEquals(JulianEra.AD, julianDate0.getEra());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      // Undeclared exception!
      try { 
        julianChronology0.dateNow((Clock) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // clock
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      List<Era> list0 = julianChronology0.eras();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      ThaiBuddhistEra thaiBuddhistEra0 = ThaiBuddhistEra.BE;
      // Undeclared exception!
      try { 
        julianChronology0.date((Era) thaiBuddhistEra0, 61, 2, 61);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // Era must be JulianEra
         //
         verifyException("org.threeten.extra.chrono.JulianChronology", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      ThaiBuddhistEra thaiBuddhistEra0 = ThaiBuddhistEra.BEFORE_BE;
      // Undeclared exception!
      try { 
        julianChronology0.dateYearDay((Era) thaiBuddhistEra0, 3, 3);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // Era must be JulianEra
         //
         verifyException("org.threeten.extra.chrono.JulianChronology", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      // Undeclared exception!
      try { 
        julianChronology0.date(63, 63, 63);
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for MonthOfYear (valid values 1 - 12): 63
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      JulianChronology julianChronology0 = JulianChronology.INSTANCE;
      TextStyle textStyle0 = TextStyle.SHORT;
      Locale locale0 = Locale.ENGLISH;
      String string0 = julianChronology0.INSTANCE.getDisplayName(textStyle0, locale0);
      assertEquals("Julian", string0);
      assertEquals("julian", julianChronology0.getCalendarType());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      JulianDate julianDate0 = julianChronology0.INSTANCE.dateYearDay(2, 2);
      assertEquals(JulianEra.AD, julianDate0.getEra());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      // Undeclared exception!
      try { 
        julianChronology0.eraOf((-1073741823));
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid era: -1073741823
         //
         verifyException("org.threeten.extra.chrono.JulianEra", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      ZonedDateTime zonedDateTime0 = MockZonedDateTime.now();
      ChronoZonedDateTime<JulianDate> chronoZonedDateTime0 = julianChronology0.INSTANCE.zonedDateTime((TemporalAccessor) zonedDateTime0);
      assertNotNull(chronoZonedDateTime0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      JulianDate julianDate0 = julianChronology0.INSTANCE.dateNow();
      assertEquals(JulianEra.AD, julianDate0.getEra());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JulianChronology julianChronology0 = new JulianChronology();
      HashMap<TemporalField, Long> hashMap0 = new HashMap<TemporalField, Long>();
      ResolverStyle resolverStyle0 = ResolverStyle.STRICT;
      JulianDate julianDate0 = julianChronology0.resolveDate(hashMap0, resolverStyle0);
      assertNull(julianDate0);
  }
}
