/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 03:08:54 GMT 2026
 */

package org.threeten.extra;

import org.junit.Test;
import static org.junit.Assert.*;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.temporal.ChronoField;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAdjuster;
import java.time.temporal.TemporalAmount;
import java.time.temporal.TemporalField;
import java.time.temporal.TemporalUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.junit.runner.RunWith;
import org.threeten.extra.MutableClock;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class MutableClock_ESTest extends MutableClock_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      ChronoField chronoField0 = ChronoField.MILLI_OF_SECOND;
      mutableClock0.set((TemporalField) chronoField0, 0L);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Instant instant0 = MockInstant.ofEpochSecond((-1034L), (-1034L));
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      MutableClock mutableClock0 = MutableClock.of(instant0, zoneOffset0);
      mutableClock0.set((TemporalAdjuster) instant0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      ChronoUnit chronoUnit0 = ChronoUnit.DECADES;
      mutableClock0.add((long) (-1), (TemporalUnit) chronoUnit0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      MutableClock mutableClock1 = mutableClock0.withZone(zoneOffset0);
      MutableClock mutableClock2 = mutableClock0.withZone(zoneOffset0);
      boolean boolean0 = mutableClock1.equals(mutableClock2);
      assertTrue(boolean0);
      assertFalse(mutableClock2.equals((Object)mutableClock0));
      assertNotSame(mutableClock2, mutableClock0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      MutableClock mutableClock1 = MutableClock.epochUTC();
      boolean boolean0 = mutableClock1.equals(mutableClock0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      Object object0 = new Object();
      boolean boolean0 = mutableClock0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      boolean boolean0 = mutableClock0.equals(mutableClock0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      ZoneOffset zoneOffset0 = ZoneOffset.UTC;
      MutableClock mutableClock1 = mutableClock0.withZone(zoneOffset0);
      assertSame(mutableClock1, mutableClock0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      MutableClock mutableClock1 = mutableClock0.withZone(zoneOffset0);
      boolean boolean0 = mutableClock0.equals(mutableClock1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      String string0 = mutableClock0.toString();
      assertEquals("MutableClock[1970-01-01T00:00:00Z,Z]", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      Instant instant0 = MockInstant.now();
      mutableClock0.setInstant(instant0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      mutableClock0.hashCode();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MutableClock mutableClock0 = MutableClock.epochUTC();
      Duration duration0 = Duration.ZERO;
      mutableClock0.add((TemporalAmount) duration0);
  }
}
