/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jun 16 19:24:03 GMT 2026
 */

package org.apache.commons.csv;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CSVParser_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.csv.CSVParser"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\xuruo\\desktop\\New_Agent_understandability_improvement 2\\scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\xuruo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CSVParser_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.csv.CSVParser$Builder",
      "org.apache.commons.io.input.AbstractInputStream",
      "org.apache.commons.csv.Token",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.csv.CSVRecord",
      "org.apache.commons.csv.Constants",
      "org.apache.commons.io.build.AbstractOrigin$PathOrigin",
      "org.apache.commons.io.build.AbstractOrigin$ByteArrayOrigin",
      "org.apache.commons.io.input.ReaderInputStream",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.io.output.AppendableOutputStream",
      "org.apache.commons.codec.binary.BaseNCodecOutputStream",
      "org.apache.commons.io.build.AbstractOrigin$RandomAccessFileOrigin",
      "org.apache.commons.csv.CSVFormat$Builder",
      "org.apache.commons.io.build.AbstractOrigin$InputStreamOrigin",
      "org.apache.commons.csv.CSVFormat",
      "org.apache.commons.io.build.AbstractOrigin$OutputStreamOrigin",
      "org.apache.commons.csv.CSVParser",
      "org.apache.commons.io.input.UnsynchronizedBufferedReader",
      "org.apache.commons.codec.binary.Base64OutputStream",
      "org.apache.commons.io.build.AbstractOrigin$WriterOrigin",
      "org.apache.commons.io.IORandomAccessFile",
      "org.apache.commons.io.file.DeleteOption",
      "org.apache.commons.csv.ExtendedBufferedReader",
      "org.apache.commons.io.input.UnsynchronizedReader",
      "org.apache.commons.io.input.Input",
      "org.apache.commons.io.Charsets",
      "org.apache.commons.io.build.AbstractOrigin$ChannelOrigin",
      "org.apache.commons.io.build.AbstractStreamBuilder",
      "org.apache.commons.csv.CSVParser$CSVRecordIterator",
      "org.apache.commons.io.build.AbstractOrigin$FileOrigin",
      "org.apache.commons.csv.QuoteMode",
      "org.apache.commons.csv.CSVParser$1",
      "org.apache.commons.io.build.AbstractOrigin$CharSequenceOrigin",
      "org.apache.commons.io.function.IOSupplier",
      "org.apache.commons.csv.DuplicateHeaderMode",
      "org.apache.commons.csv.CSVException",
      "org.apache.commons.io.build.AbstractOrigin$AbstractRandomAccessFileOrigin",
      "org.apache.commons.io.build.AbstractOriginSupplier",
      "org.apache.commons.io.build.AbstractOrigin$ReaderOrigin",
      "org.apache.commons.io.build.AbstractOrigin$IORandomAccessFileOrigin",
      "org.apache.commons.csv.Lexer",
      "org.apache.commons.csv.Token$Type",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.csv.CSVParser$Headers",
      "org.apache.commons.io.build.AbstractOrigin",
      "org.apache.commons.io.build.AbstractOrigin$URIOrigin",
      "org.apache.commons.csv.CSVPrinter"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.net.URLStreamHandler", false, CSVParser_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CSVParser_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.csv.CSVParser",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.build.AbstractOriginSupplier",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.build.AbstractStreamBuilder",
      "org.apache.commons.csv.CSVParser$Builder",
      "org.apache.commons.csv.CSVParser$CSVRecordIterator",
      "org.apache.commons.csv.CSVParser$Headers",
      "org.apache.commons.csv.Constants",
      "org.apache.commons.csv.DuplicateHeaderMode",
      "org.apache.commons.csv.CSVFormat$Builder",
      "org.apache.commons.csv.QuoteMode",
      "org.apache.commons.csv.CSVFormat",
      "org.apache.commons.csv.Token$Type",
      "org.apache.commons.csv.CSVParser$1",
      "org.apache.commons.io.build.AbstractOrigin",
      "org.apache.commons.io.build.AbstractOrigin$ReaderOrigin",
      "org.apache.commons.io.function.IOBaseStreamAdapter",
      "org.apache.commons.io.function.IOStreamAdapter",
      "org.apache.commons.csv.Token",
      "org.apache.commons.csv.Lexer",
      "org.apache.commons.io.input.UnsynchronizedReader",
      "org.apache.commons.io.input.UnsynchronizedBufferedReader",
      "org.apache.commons.csv.ExtendedBufferedReader",
      "org.apache.commons.io.input.XmlStreamReader$Builder",
      "org.apache.commons.io.Charsets",
      "org.apache.commons.io.input.Tailer",
      "org.apache.commons.io.input.Tailer$Builder",
      "org.apache.commons.io.input.UncheckedBufferedReader$Builder",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.io.input.UncheckedBufferedReader",
      "org.apache.commons.io.IORandomAccessFile",
      "org.apache.commons.io.input.Input",
      "org.apache.commons.io.input.ProxyInputStream$AbstractBuilder",
      "org.apache.commons.io.input.ThrottledInputStream$Builder",
      "org.apache.commons.io.input.ProxyInputStream",
      "org.apache.commons.io.input.CountingInputStream",
      "org.apache.commons.io.input.ThrottledInputStream",
      "org.apache.commons.io.output.FileWriterWithEncoding$Builder",
      "org.apache.commons.io.output.ProxyWriter",
      "org.apache.commons.io.output.FileWriterWithEncoding",
      "org.apache.commons.csv.CSVFormat$Predefined",
      "org.apache.commons.io.build.AbstractOrigin$ByteArrayOrigin",
      "org.apache.commons.io.input.CharSequenceInputStream$Builder",
      "org.apache.commons.io.input.CharSequenceInputStream",
      "org.apache.commons.io.input.AbstractInputStream",
      "org.apache.commons.io.input.ReaderInputStream",
      "org.apache.commons.io.input.BufferedFileChannelInputStream$Builder",
      "org.apache.commons.io.input.BufferedFileChannelInputStream",
      "org.apache.commons.io.input.UncheckedFilterReader$Builder",
      "org.apache.commons.io.input.UncheckedFilterReader",
      "org.apache.commons.io.ByteOrderMark",
      "org.apache.commons.io.input.XmlStreamReader",
      "org.apache.commons.csv.CSVRecord",
      "org.apache.commons.io.input.ReaderInputStream$Builder",
      "org.apache.commons.io.build.AbstractOrigin$FileOrigin",
      "org.apache.commons.io.output.XmlStreamWriter$Builder",
      "org.apache.commons.io.output.XmlStreamWriter",
      "org.apache.commons.csv.CSVPrinter",
      "org.apache.commons.io.output.ChunkedOutputStream$Builder",
      "org.apache.commons.io.output.ChunkedOutputStream",
      "org.apache.commons.io.function.IOStream$1",
      "org.apache.commons.io.function.IOStreams",
      "org.apache.commons.csv.CSVFormat$1",
      "org.apache.commons.io.output.FlushShieldOutputStream$Builder",
      "org.apache.commons.io.output.ProxyOutputStream",
      "org.apache.commons.io.output.FlushShieldOutputStream",
      "org.apache.commons.io.function.IOConsumer",
      "org.apache.commons.io.function.Erase",
      "org.apache.commons.io.input.ChecksumInputStream$Builder",
      "org.apache.commons.io.input.ChecksumInputStream",
      "org.apache.commons.io.input.QueueInputStream$Builder",
      "org.apache.commons.io.input.QueueInputStream",
      "org.apache.commons.io.input.CloseShieldInputStream$Builder",
      "org.apache.commons.io.input.CloseShieldInputStream",
      "org.apache.commons.io.input.RandomAccessFileInputStream$Builder",
      "org.apache.commons.io.input.AutoCloseInputStream$Builder",
      "org.apache.commons.io.input.AutoCloseInputStream",
      "org.apache.commons.io.build.AbstractOrigin$PathOrigin",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.input.UncheckedFilterInputStream$Builder",
      "org.apache.commons.io.input.UncheckedFilterInputStream",
      "org.apache.commons.io.input.UnsynchronizedFilterInputStream$Builder",
      "org.apache.commons.io.input.UnsynchronizedFilterInputStream",
      "org.apache.commons.io.output.UncheckedFilterOutputStream$Builder",
      "org.apache.commons.io.output.UncheckedFilterOutputStream",
      "org.apache.commons.io.input.MemoryMappedFileInputStream$Builder",
      "org.apache.commons.io.input.MemoryMappedFileInputStream",
      "org.apache.commons.io.input.BOMInputStream$Builder",
      "org.apache.commons.io.input.BOMInputStream",
      "org.apache.commons.io.function.Constants",
      "org.apache.commons.io.output.DeferredFileOutputStream$Builder",
      "org.apache.commons.io.output.ThresholdingOutputStream",
      "org.apache.commons.io.output.DeferredFileOutputStream",
      "org.apache.commons.io.output.AbstractByteArrayOutputStream",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.csv.CSVException",
      "org.apache.commons.io.output.WriterOutputStream$Builder",
      "org.apache.commons.io.output.WriterOutputStream",
      "org.apache.commons.io.build.AbstractOrigin$AbstractRandomAccessFileOrigin",
      "org.apache.commons.io.build.AbstractOrigin$IORandomAccessFileOrigin",
      "org.apache.commons.io.build.AbstractOrigin$ChannelOrigin",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.charset.CharsetEncoders",
      "org.apache.commons.io.output.LockableFileWriter$Builder",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.output.LockableFileWriter",
      "org.apache.commons.io.input.ObservableInputStream$AbstractBuilder",
      "org.apache.commons.io.input.ObservableInputStream$Builder",
      "org.apache.commons.io.input.ObservableInputStream",
      "org.apache.commons.io.build.AbstractOrigin$OutputStreamOrigin",
      "org.apache.commons.io.build.AbstractOrigin$RandomAccessFileOrigin",
      "org.apache.commons.io.input.UnsynchronizedBufferedInputStream$Builder",
      "org.apache.commons.io.input.UnsynchronizedBufferedInputStream",
      "org.apache.commons.io.input.TailerListenerAdapter",
      "org.apache.commons.io.input.MessageDigestInputStream$Builder",
      "org.apache.commons.io.input.BoundedInputStream$AbstractBuilder",
      "org.apache.commons.io.input.BoundedInputStream$Builder",
      "org.apache.commons.io.input.BoundedInputStream",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.io.input.ReadAheadInputStream$Builder",
      "org.apache.commons.io.input.ReadAheadInputStream",
      "org.apache.commons.io.input.ObservableInputStream$Observer",
      "org.apache.commons.io.input.MessageDigestInputStream$MessageDigestMaintainingObserver",
      "org.apache.commons.io.output.ProxyOutputStream$Builder",
      "org.apache.commons.io.input.UnsynchronizedByteArrayInputStream$Builder",
      "org.apache.commons.io.input.UnsynchronizedByteArrayInputStream",
      "org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder",
      "org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream",
      "org.apache.commons.io.build.AbstractOrigin$WriterOrigin",
      "org.apache.commons.io.output.UncheckedFilterWriter$Builder",
      "org.apache.commons.io.output.UncheckedFilterWriter",
      "org.apache.commons.io.input.RandomAccessFileInputStream",
      "org.apache.commons.io.build.AbstractOrigin$URIOrigin",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.IOExceptionList"
    );
  }
}
