/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jun 16 20:45:54 GMT 2026
 */

package org.apache.commons.csv;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Lexer_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.csv.Lexer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\xuruo\\desktop\\New_Agent_understandability_improvement 2\\scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\xuruo\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Lexer_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.io.input.BoundedInputStream",
      "org.apache.commons.csv.Token",
      "org.apache.commons.io.output.NullWriter",
      "org.apache.commons.csv.Constants",
      "org.apache.commons.io.output.AppendableOutputStream",
      "org.apache.commons.codec.binary.BaseNCodecOutputStream",
      "org.apache.commons.io.input.CharSequenceReader",
      "org.apache.commons.io.CloseableURLConnection",
      "org.apache.commons.csv.CSVFormat$Builder",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.csv.CSVFormat",
      "org.apache.commons.io.output.AppendableWriter",
      "org.apache.commons.io.output.StringBuilderWriter",
      "org.apache.commons.csv.CSVParser",
      "org.apache.commons.io.input.UnsynchronizedBufferedReader",
      "org.apache.commons.codec.binary.Base64OutputStream",
      "org.apache.commons.csv.ExtendedBufferedReader",
      "org.apache.commons.io.input.UnsynchronizedReader",
      "org.apache.commons.io.input.Input",
      "org.apache.commons.io.output.AbstractByteArrayOutputStream",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.io.output.QueueOutputStream",
      "org.apache.commons.csv.QuoteMode",
      "org.apache.commons.csv.DuplicateHeaderMode",
      "org.apache.commons.csv.CSVException",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.csv.Lexer",
      "org.apache.commons.io.output.NullOutputStream",
      "org.apache.commons.csv.Token$Type",
      "org.apache.commons.io.function.IOStream",
      "org.apache.commons.io.input.ProxyInputStream",
      "org.apache.commons.io.function.IOBaseStream",
      "org.apache.commons.csv.CSVPrinter"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Lexer_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.csv.Lexer",
      "org.apache.commons.csv.Token$Type",
      "org.apache.commons.csv.CSVFormat$Builder",
      "org.apache.commons.csv.Constants",
      "org.apache.commons.csv.QuoteMode",
      "org.apache.commons.csv.CSVFormat",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.build.AbstractOriginSupplier",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.build.AbstractStreamBuilder",
      "org.apache.commons.io.input.UncheckedFilterReader$Builder",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.io.input.UncheckedFilterReader",
      "org.apache.commons.io.input.UnsynchronizedReader",
      "org.apache.commons.io.input.UnsynchronizedBufferedReader",
      "org.apache.commons.csv.ExtendedBufferedReader",
      "org.apache.commons.io.input.Input",
      "org.apache.commons.io.input.XmlStreamReader$Builder",
      "org.apache.commons.io.ByteOrderMark",
      "org.apache.commons.io.input.XmlStreamReader",
      "org.apache.commons.io.input.UncheckedBufferedReader$Builder",
      "org.apache.commons.io.input.UncheckedBufferedReader",
      "org.apache.commons.io.input.Tailer",
      "org.apache.commons.io.input.Tailer$Builder",
      "org.apache.commons.csv.CSVFormat$Predefined",
      "org.apache.commons.csv.Token",
      "org.apache.commons.io.function.IOBaseStreamAdapter",
      "org.apache.commons.io.function.IOStreamAdapter",
      "org.apache.commons.io.function.Constants",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.csv.CSVPrinter",
      "org.apache.commons.csv.CSVFormat$1",
      "org.apache.commons.csv.CSVException",
      "org.apache.commons.csv.CSVParser",
      "org.apache.commons.csv.CSVParser$Builder",
      "org.apache.commons.io.build.AbstractOrigin",
      "org.apache.commons.io.build.AbstractOrigin$ReaderOrigin",
      "org.apache.commons.csv.CSVParser$CSVRecordIterator",
      "org.apache.commons.csv.CSVParser$Headers",
      "org.apache.commons.io.function.IOStream$1",
      "org.apache.commons.io.function.IOStreams",
      "org.apache.commons.io.output.FileWriterWithEncoding$Builder",
      "org.apache.commons.io.output.ProxyWriter",
      "org.apache.commons.io.output.FileWriterWithEncoding",
      "org.apache.commons.io.function.IOConsumer",
      "org.apache.commons.io.function.Erase",
      "org.apache.commons.io.IOUtils$ScratchChars",
      "org.apache.commons.io.Charsets",
      "org.apache.commons.io.output.UncheckedFilterWriter$Builder",
      "org.apache.commons.io.output.UncheckedFilterWriter",
      "org.apache.commons.io.IORandomAccessFile",
      "org.apache.commons.io.output.FlushShieldOutputStream$Builder",
      "org.apache.commons.io.output.ProxyOutputStream",
      "org.apache.commons.io.output.FlushShieldOutputStream",
      "org.apache.commons.io.output.UncheckedFilterOutputStream$Builder",
      "org.apache.commons.io.output.UncheckedFilterOutputStream",
      "org.apache.commons.io.output.ChunkedOutputStream$Builder",
      "org.apache.commons.io.output.ChunkedOutputStream",
      "org.apache.commons.io.output.LockableFileWriter$Builder",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.build.AbstractOrigin$FileOrigin",
      "org.apache.commons.io.output.LockableFileWriter",
      "org.apache.commons.io.output.WriterOutputStream$Builder",
      "org.apache.commons.csv.DuplicateHeaderMode"
    );
  }
}
