/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jun 16 07:05:14 GMT 2026
 */

package com.itextpdf.text.pdf.fonts.cmaps;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CMapParserEx_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.itextpdf.text.pdf.fonts.cmaps.CMapParserEx"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.home", "/Users/tenghaha"); 
    java.lang.System.setProperty("user.dir", "/Users/tenghaha/Projects/New_Agent_understandability_improvement/scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/y7/5v6zwzln5s14jn6cndl4lq7m0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CMapParserEx_ESTest_scaffolding.class.getClassLoader() ,
      "com.itextpdf.text.pdf.ByteBuffer",
      "com.itextpdf.text.ExceptionConverter",
      "com.itextpdf.text.pdf.PdfContentParser$1",
      "com.itextpdf.text.pdf.ExtraEncoding",
      "com.itextpdf.text.pdf.interfaces.PdfPageActions",
      "com.itextpdf.text.pdf.PdfNumber",
      "com.itextpdf.text.exceptions.InvalidPdfException",
      "com.itextpdf.text.pdf.PdfWriter",
      "com.itextpdf.text.pdf.IntHashtable$Entry",
      "com.itextpdf.text.pdf.PdfEncodings$SymbolConversion",
      "com.itextpdf.text.pdf.PdfEncodings",
      "com.itextpdf.text.pdf.PdfArray",
      "com.itextpdf.text.pdf.fonts.cmaps.CidResource",
      "com.itextpdf.text.io.StreamUtil",
      "com.itextpdf.text.pdf.PRTokeniser$TokenType",
      "com.itextpdf.text.pdf.interfaces.PdfRunDirection",
      "com.itextpdf.text.pdf.PdfContentParser",
      "com.itextpdf.text.pdf.interfaces.PdfVersion",
      "com.itextpdf.text.DocListener",
      "com.itextpdf.text.pdf.PdfLiteral",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapParserEx",
      "com.itextpdf.text.pdf.fonts.cmaps.CidLocationFromByte",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapCidByte",
      "com.itextpdf.text.pdf.PdfEncodings$SymbolTTConversion",
      "com.itextpdf.text.ElementListener",
      "com.itextpdf.text.pdf.PdfString",
      "com.itextpdf.text.pdf.PRTokeniser",
      "com.itextpdf.text.pdf.interfaces.PdfDocumentActions",
      "com.itextpdf.text.pdf.interfaces.PdfAnnotations",
      "com.itextpdf.text.pdf.IntHashtable",
      "com.itextpdf.text.pdf.PdfNull",
      "com.itextpdf.text.pdf.PdfName",
      "com.itextpdf.text.io.ArrayRandomAccessSource",
      "com.itextpdf.text.pdf.PdfObject",
      "com.itextpdf.text.Element",
      "com.itextpdf.text.io.RandomAccessSource",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapCidUni",
      "com.itextpdf.text.DocWriter",
      "com.itextpdf.text.Rectangle",
      "com.itextpdf.text.pdf.fonts.cmaps.CidLocation",
      "com.itextpdf.text.pdf.PdfEncodings$WingdingsConversion",
      "com.itextpdf.text.pdf.fonts.cmaps.AbstractCMap",
      "com.itextpdf.text.pdf.RandomAccessFileOrArray",
      "com.itextpdf.text.error_messages.MessageLocalization",
      "com.itextpdf.text.DocumentException",
      "com.itextpdf.text.pdf.interfaces.PdfViewerPreferences",
      "com.itextpdf.text.pdf.PdfDictionary",
      "com.itextpdf.text.pdf.PdfEncodings$Cp437Conversion",
      "com.itextpdf.text.io.RandomAccessSourceFactory",
      "com.itextpdf.text.pdf.interfaces.PdfEncryptionSettings",
      "com.itextpdf.text.io.MapFailedException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CMapParserEx_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.itextpdf.text.pdf.PdfObject",
      "com.itextpdf.text.pdf.ByteBuffer",
      "com.itextpdf.text.pdf.PdfName",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapParserEx",
      "com.itextpdf.text.io.StreamUtil",
      "com.itextpdf.text.error_messages.MessageLocalization",
      "com.itextpdf.text.pdf.fonts.cmaps.AbstractCMap",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapToUnicode",
      "com.itextpdf.text.Utilities",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapByteCid",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapSequence",
      "com.itextpdf.text.pdf.fonts.cmaps.CidResource",
      "com.itextpdf.text.pdf.fonts.cmaps.CidLocationFromByte",
      "com.itextpdf.text.pdf.PRTokeniser",
      "com.itextpdf.text.pdf.RandomAccessFileOrArray",
      "com.itextpdf.text.io.RandomAccessSourceFactory",
      "com.itextpdf.text.io.ArrayRandomAccessSource",
      "com.itextpdf.text.pdf.PdfContentParser",
      "com.itextpdf.text.pdf.PRTokeniser$TokenType",
      "com.itextpdf.text.pdf.PdfContentParser$1",
      "com.itextpdf.text.pdf.PdfLiteral",
      "com.itextpdf.text.pdf.IntHashtable",
      "com.itextpdf.text.pdf.IntHashtable$Entry",
      "com.itextpdf.text.pdf.PdfEncodings$WingdingsConversion",
      "com.itextpdf.text.pdf.PdfEncodings$SymbolConversion",
      "com.itextpdf.text.pdf.PdfEncodings$SymbolTTConversion",
      "com.itextpdf.text.pdf.PdfEncodings$Cp437Conversion",
      "com.itextpdf.text.pdf.PdfEncodings",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapUniCid",
      "com.itextpdf.text.DocWriter",
      "com.itextpdf.text.pdf.codec.Base64",
      "com.itextpdf.text.log.DefaultCounter",
      "com.itextpdf.text.log.CounterFactory",
      "com.itextpdf.text.pdf.PdfWriter",
      "com.itextpdf.text.Document",
      "com.itextpdf.text.pdf.PdfDocument",
      "com.itextpdf.text.Rectangle",
      "com.itextpdf.text.RectangleReadOnly",
      "com.itextpdf.text.PageSize",
      "com.itextpdf.text.AccessibleElementId",
      "com.itextpdf.text.pdf.PdfDocument$Indentation",
      "com.itextpdf.text.pdf.PdfDictionary",
      "com.itextpdf.text.pdf.PdfDocument$PdfInfo",
      "com.itextpdf.text.pdf.PdfString",
      "com.itextpdf.text.Version",
      "com.itextpdf.text.UnifiedVersion",
      "com.itextpdf.commons.actions.AbstractITextEvent",
      "com.itextpdf.commons.actions.AbstractITextConfigurationEvent",
      "com.itextpdf.text.UnifiedVersionUtil$UnifiedVersionEvent",
      "com.itextpdf.text.UnifiedVersionUtil",
      "com.itextpdf.commons.actions.data.ProductData",
      "com.itextpdf.text.actions.data.IText5ProductData",
      "com.itextpdf.commons.actions.AbstractContextBasedEventHandler",
      "com.itextpdf.commons.actions.contexts.UnknownContext",
      "com.itextpdf.commons.actions.ProductEventHandler",
      "com.itextpdf.commons.actions.ProductNameConstant",
      "com.itextpdf.text.pdf.PdfDate",
      "com.itextpdf.text.pdf.internal.PdfViewerPreferencesImp",
      "com.itextpdf.text.Meta",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapCidUni",
      "com.itextpdf.text.pdf.PdfArray",
      "com.itextpdf.text.pdf.fonts.cmaps.CMapCidByte",
      "com.itextpdf.text.pdf.PdfNumber",
      "com.itextpdf.text.pdf.PdfDestination",
      "com.itextpdf.text.exceptions.InvalidPdfException",
      "com.itextpdf.text.pdf.PdfContentByte",
      "com.itextpdf.text.pdf.PdfTemplate",
      "com.itextpdf.text.pdf.PdfAppearance",
      "com.itextpdf.text.pdf.OutputStreamCounter",
      "com.itextpdf.text.pdf.PdfPages",
      "com.itextpdf.text.pdf.internal.PdfVersionImp",
      "com.itextpdf.text.pdf.internal.PdfXConformanceImp",
      "com.itextpdf.text.pdf.PdfContentByte$GraphicState",
      "com.itextpdf.text.BaseColor",
      "com.itextpdf.text.pdf.ExtendedColor",
      "com.itextpdf.text.pdf.GrayColor",
      "com.itextpdf.awt.geom.AffineTransform",
      "com.itextpdf.text.pdf.internal.PdfAnnotationsImp",
      "com.itextpdf.text.pdf.PdfAcroForm",
      "com.itextpdf.text.pdf.PageResources",
      "com.itextpdf.text.pdf.PdfLayer",
      "com.itextpdf.text.pdf.PdfArtifact",
      "com.itextpdf.text.pdf.PdfPCell",
      "com.itextpdf.text.pdf.ColumnText",
      "com.itextpdf.text.log.NoOpLogger",
      "com.itextpdf.text.log.LoggerFactory",
      "com.itextpdf.text.pdf.PdfReader",
      "com.itextpdf.text.pdf.PdfPTable",
      "com.itextpdf.text.Image",
      "com.itextpdf.text.pdf.PdfPTableBody",
      "com.itextpdf.text.pdf.PdfPTableHeader",
      "com.itextpdf.text.pdf.PdfPTableFooter",
      "com.itextpdf.text.pdf.ReaderProperties",
      "com.itextpdf.text.pdf.PdfPHeaderCell",
      "com.itextpdf.text.pdf.PdfNull",
      "com.itextpdf.text.pdf.PdfStructureElement",
      "com.itextpdf.text.pdf.StringUtils",
      "com.itextpdf.text.ExceptionConverter",
      "com.itextpdf.text.ImgWMF",
      "com.itextpdf.text.ImgRaw",
      "com.itextpdf.text.DocumentException",
      "com.itextpdf.text.BadElementException",
      "com.itextpdf.text.List",
      "com.itextpdf.text.GreekList",
      "com.itextpdf.text.Font",
      "com.itextpdf.text.Font$FontFamily",
      "com.itextpdf.text.TabSplitCharacter",
      "com.itextpdf.text.Chunk",
      "com.itextpdf.text.FontFactoryImp",
      "com.itextpdf.text.FontFactory",
      "com.itextpdf.text.pdf.BaseFont",
      "com.itextpdf.text.pdf.Type1Font",
      "com.itextpdf.text.pdf.fonts.FontsResourceAnchor",
      "com.itextpdf.text.pdf.PdfAnnotation",
      "com.itextpdf.text.pdf.PdfFormField",
      "com.itextpdf.text.pdf.PdfGState",
      "com.itextpdf.text.Jpeg2000",
      "com.itextpdf.text.ImgCCITT",
      "com.itextpdf.text.pdf.PdfArtifact$1",
      "org.bouncycastle.asn1.ASN1Object",
      "org.bouncycastle.asn1.ASN1Primitive",
      "org.bouncycastle.asn1.ASN1Type",
      "org.bouncycastle.asn1.ASN1UniversalType",
      "org.bouncycastle.asn1.ASN1BitString$1",
      "org.bouncycastle.asn1.ASN1Tag",
      "org.bouncycastle.asn1.ASN1BitString",
      "org.bouncycastle.asn1.DERBitString",
      "org.bouncycastle.util.Arrays",
      "org.bouncycastle.asn1.x509.Certificate",
      "org.bouncycastle.asn1.ASN1Sequence$1",
      "org.bouncycastle.asn1.ASN1Sequence",
      "com.itextpdf.text.pdf.codec.wmf.InputMeta",
      "com.itextpdf.text.pdf.collection.PdfTargetDictionary",
      "com.itextpdf.text.pdf.PdfAction",
      "com.itextpdf.text.pdf.PdfBoolean",
      "com.itextpdf.text.pdf.PdfDashPattern",
      "com.itextpdf.text.pdf.PdfBorderArray",
      "com.itextpdf.text.ImgJBIG2",
      "com.itextpdf.text.Jpeg",
      "com.itextpdf.text.pdf.codec.PngImage",
      "com.itextpdf.text.pdf.NumberArray",
      "com.itextpdf.text.pdf.PdfRectangle",
      "com.itextpdf.text.pdf.PdfStream",
      "com.itextpdf.text.pdf.PdfFormXObject",
      "com.itextpdf.text.ImgTemplate",
      "com.itextpdf.text.pdf.PdfFileSpecification",
      "com.itextpdf.text.pdf.PdfSpotColor",
      "com.itextpdf.text.pdf.PdfOCProperties",
      "com.itextpdf.text.Header",
      "com.itextpdf.text.pdf.PdfTransparencyGroup",
      "com.itextpdf.text.pdf.collection.PdfCollectionSort",
      "com.itextpdf.text.pdf.PdfOutline",
      "com.itextpdf.text.pdf.PdfColor"
    );
  }
}
