/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 07:05:14 GMT 2026
 */

package com.itextpdf.text.pdf.fonts.cmaps;

import org.junit.Test;
import static org.junit.Assert.*;
import com.itextpdf.text.DocWriter;
import com.itextpdf.text.pdf.fonts.cmaps.CMapCidByte;
import com.itextpdf.text.pdf.fonts.cmaps.CMapCidUni;
import com.itextpdf.text.pdf.fonts.cmaps.CMapParserEx;
import com.itextpdf.text.pdf.fonts.cmaps.CidLocationFromByte;
import com.itextpdf.text.pdf.fonts.cmaps.CidResource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CMapParserEx_ESTest extends CMapParserEx_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CMapCidUni cMapCidUni0 = new CMapCidUni();
      byte[] byteArray0 = DocWriter.getISOBytes("A]usecmap");
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("A]usecmap", cMapCidUni0, cidLocationFromByte0);
      assertNull(cMapCidUni0.getRegistry());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CMapCidUni cMapCidUni0 = new CMapCidUni();
      byte[] byteArray0 = DocWriter.getISOBytes("usecmap");
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("usecmap", cMapCidUni0, cidLocationFromByte0);
      assertEquals(0, cMapCidUni0.getSupplement());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CMapCidUni cMapCidUni0 = new CMapCidUni();
      byte[] byteArray0 = DocWriter.getISOBytes("endbfrange");
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("endbfrange", cMapCidUni0, cidLocationFromByte0);
      assertNull(cMapCidUni0.getName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = DocWriter.getISOBytes("endcidrange");
      CMapCidByte cMapCidByte0 = new CMapCidByte();
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("endcidrange", cMapCidByte0, cidLocationFromByte0);
      assertNull(cMapCidByte0.getRegistry());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CMapCidUni cMapCidUni0 = new CMapCidUni();
      byte[] byteArray0 = DocWriter.getISOBytes("endbfchar");
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("endbfchar", cMapCidUni0, cidLocationFromByte0);
      assertNull(cMapCidUni0.getOrdering());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CMapCidByte cMapCidByte0 = new CMapCidByte();
      byte[] byteArray0 = DocWriter.getISOBytes("endcidchar");
      CidLocationFromByte cidLocationFromByte0 = new CidLocationFromByte(byteArray0);
      CMapParserEx.parseCid("endcidchar", cMapCidByte0, cidLocationFromByte0);
      assertNull(cMapCidByte0.getRegistry());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CMapParserEx cMapParserEx0 = new CMapParserEx();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CMapCidUni cMapCidUni0 = new CMapCidUni();
      CidResource cidResource0 = new CidResource();
      CMapParserEx.parseCid("CMapByteCid.class", cMapCidUni0, cidResource0);
      assertNull(cMapCidUni0.getOrdering());
  }
}
