/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 06:35:54 GMT 2026
 */

package com.itextpdf.text;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.ListBody;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.ListLabel;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ListItem_ESTest extends ListItem_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ListItem listItem0 = new ListItem(1.0F, "");
      ListBody listBody0 = listItem0.getListBody();
      ListBody listBody1 = listItem0.getListBody();
      assertSame(listBody1, listBody0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ListItem listItem0 = new ListItem(1.0F, "");
      listItem0.add("");
      Chunk chunk0 = Chunk.TABBING;
      listItem0.setListSymbol(chunk0);
      listItem0.adjustListSymbolFont();
      assertEquals((-1), listItem0.getAlignment());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ListItem listItem0 = new ListItem("com.itextpdf.text.ListItem");
      ListItem listItem1 = (ListItem)listItem0.cloneShallow(true);
      listItem1.adjustListSymbolFont();
      assertTrue(listItem1.hasLeading());
      assertEquals(18.0F, listItem1.getTotalLeading(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ListItem listItem0 = new ListItem(1.0F, "");
      listItem0.add("");
      listItem0.adjustListSymbolFont();
      assertTrue(listItem0.isNestable());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ListItem listItem0 = new ListItem(1.0F, "");
      listItem0.setIndentationLeft((-3235.8F), false);
      assertEquals((-3235.8F), listItem0.getIndentationLeft(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ListItem listItem0 = new ListItem("com.itextpdf.text.ListItem");
      Chunk chunk0 = Chunk.createWhitespace("PDF");
      Font.FontFamily font_FontFamily0 = Font.FontFamily.HELVETICA;
      Font font0 = new Font(font_FontFamily0, 922.3813F, (-2420));
      ListItem listItem1 = new ListItem("BACKGROUND", font0);
      listItem1.setListSymbol(chunk0);
      listItem0.setListSymbol(chunk0);
      assertNotSame(listItem0, listItem1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ListItem listItem0 = new ListItem(1.0F, "");
      Chunk chunk0 = Chunk.TABBING;
      listItem0.setListSymbol(chunk0);
      listItem0.setListSymbol(chunk0);
      assertEquals(0.0F, listItem0.getMultipliedLeading(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Phrase phrase0 = new Phrase(0.0F);
      ListItem listItem0 = new ListItem(phrase0);
      assertEquals(0.0F, listItem0.getIndentationRight(), 0.01F);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Font.FontFamily font_FontFamily0 = Font.FontFamily.TIMES_ROMAN;
      Font font0 = new Font(font_FontFamily0);
      ListItem listItem0 = new ListItem(3000.586F, "com.itextpdf.text.ListItem", font0);
      // Undeclared exception!
      try { 
        listItem0.setIndentationLeft(0.0F, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.itextpdf.text.ListItem", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VerticalPositionMark verticalPositionMark0 = new VerticalPositionMark();
      Chunk chunk0 = new Chunk(verticalPositionMark0, false);
      ListItem listItem0 = new ListItem(chunk0);
      assertEquals(1, listItem0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ListItem listItem0 = new ListItem(0.0F);
      listItem0.getListLabel();
      ListLabel listLabel0 = listItem0.getListLabel();
      assertFalse(listLabel0.getTagLabelContent());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ListItem listItem0 = new ListItem("com.itextpdf.text.ListItem");
      int int0 = listItem0.type();
      assertEquals(15, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Chunk chunk0 = Chunk.createWhitespace("invalid_", false);
      ListItem listItem0 = new ListItem((-1391.7872F), chunk0);
      Paragraph paragraph0 = listItem0.cloneShallow(false);
      assertEquals(0, paragraph0.size());
      assertEquals((-1391.7872F), paragraph0.getTotalLeading(), 0.01F);
  }
}
