/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 22:36:03 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Authenticator;
import java.net.InetAddress;
import java.net.PasswordAuthentication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.jsoup.helper.AuthenticationHandler;
import org.jsoup.helper.RequestAuthenticator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class AuthenticationHandler_ESTest extends AuthenticationHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuthenticationHandler authenticationHandler0 = new AuthenticationHandler();
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler0 = (AuthenticationHandler.GlobalHandler)AuthenticationHandler.handler;
      AuthenticationHandler.handler = (AuthenticationHandler.AuthShim) authenticationHandler_GlobalHandler0;
      authenticationHandler0.getPasswordAuthentication();
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler1 = new AuthenticationHandler.GlobalHandler();
      InetAddress inetAddress0 = MockInetAddress.getByName(",L\"?KF91pvtJ0''");
      MockInetAddress.getLocalHost();
      PasswordAuthentication passwordAuthentication0 = Authenticator.requestPasswordAuthentication("", inetAddress0, 0, "MVz", ",L\"?KF91pvtJ0''", "");
      assertNull(passwordAuthentication0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler0 = new AuthenticationHandler.GlobalHandler();
      authenticationHandler_GlobalHandler0.remove();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler0 = (AuthenticationHandler.GlobalHandler)AuthenticationHandler.handler;
      authenticationHandler_GlobalHandler0.enable((RequestAuthenticator) null, "f#=DA&6^'(,,XQ");
  }
}
