/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jun 15 20:34:32 GMT 2026
 */

package org.jsoup.helper;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CookieUtil_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.jsoup.helper.CookieUtil"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/tenghaha/Projects/New_Agent_understandability_improvement/scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/y7/5v6zwzln5s14jn6cndl4lq7m0000gn/T/"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CookieUtil_ESTest_scaffolding.class.getClassLoader() ,
      "org.jsoup.helper.DataUtil",
      "org.jsoup.Connection$Response",
      "org.jsoup.parser.TokenData",
      "org.jsoup.parser.TreeBuilder",
      "org.jsoup.select.Evaluator$IndexEvaluator",
      "org.jsoup.select.Evaluator$IsOnlyOfType",
      "org.jsoup.select.Evaluator$TagStartsWith",
      "org.jsoup.select.Evaluator$IsEmpty",
      "org.jsoup.parser.Parser",
      "org.jsoup.select.Evaluator$ContainsWholeText",
      "org.jsoup.internal.ControllableInputStream",
      "org.jsoup.select.Evaluator$AttributeWithValueMatching",
      "org.jsoup.nodes.Element",
      "org.jsoup.select.Evaluator$IsNthChild",
      "org.jsoup.helper.HttpConnection",
      "org.jsoup.select.Evaluator$Class",
      "org.jsoup.parser.Token",
      "org.jsoup.select.Evaluator$MatchesOwn",
      "org.jsoup.select.Evaluator$AttributeKeyPair",
      "org.jsoup.select.StructuralEvaluator$Ancestor",
      "org.jsoup.select.Evaluator$ContainsWholeOwnText",
      "org.jsoup.select.Evaluator$IsNthLastOfType",
      "org.jsoup.select.CombiningEvaluator$And",
      "org.jsoup.select.Evaluator$IsLastOfType",
      "org.jsoup.select.Evaluator$Attribute",
      "org.jsoup.parser.Token$EndTag",
      "org.jsoup.helper.HttpConnection$Request",
      "org.jsoup.nodes.Document",
      "org.jsoup.Connection$KeyVal",
      "org.jsoup.select.Evaluator$AttributeWithValueContaining",
      "org.jsoup.parser.HtmlTreeBuilder",
      "org.jsoup.select.Evaluator$AllElements",
      "org.jsoup.nodes.FormElement",
      "org.jsoup.UnsupportedMimeTypeException",
      "org.jsoup.select.StructuralEvaluator",
      "org.jsoup.nodes.TextNode",
      "org.jsoup.select.Evaluator$AttributeWithValue",
      "org.jsoup.select.Evaluator$AttributeWithValueNot",
      "org.jsoup.parser.ParseErrorList",
      "org.jsoup.select.NodeEvaluator$InstanceType",
      "org.jsoup.select.NodeEvaluator$MatchesValue",
      "org.jsoup.select.CombiningEvaluator$Or",
      "org.jsoup.select.Evaluator$ContainsText",
      "org.jsoup.Connection$Base",
      "org.jsoup.select.Evaluator$Id",
      "org.jsoup.select.Evaluator$IsNthOfType",
      "org.jsoup.parser.StreamParser",
      "org.jsoup.select.StructuralEvaluator$PreviousSibling",
      "org.jsoup.select.Evaluator$IndexEquals",
      "org.jsoup.select.NodeEvaluator$BlankValue",
      "org.jsoup.select.Selector$SelectorParseException",
      "org.jsoup.helper.ValidationException",
      "org.jsoup.select.StructuralEvaluator$Not",
      "org.jsoup.parser.Token$Tag",
      "org.jsoup.helper.CookieUtil",
      "org.jsoup.parser.CharacterReader",
      "org.jsoup.select.Evaluator$IsFirstChild",
      "org.jsoup.select.Evaluator$Tag",
      "org.jsoup.select.StructuralEvaluator$Root",
      "org.jsoup.helper.HttpConnection$Response",
      "org.jsoup.select.NodeEvaluator",
      "org.jsoup.internal.StringUtil",
      "org.jsoup.select.Evaluator$AttributeWithValueStarting",
      "org.jsoup.parser.Token$StartTag",
      "org.jsoup.nodes.Comment",
      "org.jsoup.Connection$Request",
      "org.jsoup.select.Evaluator$IndexGreaterThan",
      "org.jsoup.nodes.LeafNode",
      "org.jsoup.HttpStatusException",
      "org.jsoup.select.QueryParser",
      "org.jsoup.internal.SimpleStreamReader",
      "org.jsoup.select.Evaluator$MatchesWholeText",
      "org.jsoup.select.Evaluator$Matches",
      "org.jsoup.select.Selector",
      "org.jsoup.select.Evaluator$AttributeWithValueEnding",
      "org.jsoup.select.Evaluator$IsOnlyChild",
      "org.jsoup.select.StructuralEvaluator$ImmediatePreviousSibling",
      "org.jsoup.select.NodeEvaluator$ContainsValue",
      "org.jsoup.Connection$Method",
      "org.jsoup.helper.HttpConnection$Base",
      "org.jsoup.parser.TokenQueue",
      "org.jsoup.parser.ParseSettings",
      "org.jsoup.select.Evaluator$MatchesWholeOwnText",
      "org.jsoup.nodes.Node",
      "org.jsoup.select.Evaluator$AttributeStarting",
      "org.jsoup.select.Evaluator$ContainsOwnText",
      "org.jsoup.nodes.DataNode",
      "org.jsoup.select.Evaluator$IndexLessThan",
      "org.jsoup.parser.XmlTreeBuilder",
      "org.jsoup.select.Evaluator$MatchText",
      "org.jsoup.select.CombiningEvaluator",
      "org.jsoup.select.Evaluator",
      "org.jsoup.Connection",
      "org.jsoup.select.Evaluator$ContainsData",
      "org.jsoup.select.Evaluator$IsRoot",
      "org.jsoup.internal.SoftPool",
      "org.jsoup.internal.Normalizer",
      "org.jsoup.nodes.CDataNode",
      "org.jsoup.helper.Validate",
      "org.jsoup.select.Evaluator$IsLastChild",
      "org.jsoup.select.StructuralEvaluator$ImmediateParentRun",
      "org.jsoup.select.Evaluator$IsNthLastChild",
      "org.jsoup.helper.RequestAuthenticator",
      "org.jsoup.parser.Token$TokenType",
      "org.jsoup.select.Evaluator$CssNthEvaluator",
      "org.jsoup.select.Evaluator$IsFirstOfType"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.function.BiConsumer", false, CookieUtil_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CookieUtil_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.jsoup.helper.CookieUtil",
      "org.jsoup.helper.HttpConnection$Base",
      "org.jsoup.helper.HttpConnection$Request",
      "org.jsoup.select.Selector",
      "org.jsoup.select.QueryParser",
      "org.jsoup.helper.Validate",
      "org.jsoup.parser.TokenQueue",
      "org.jsoup.internal.SoftPool",
      "org.jsoup.parser.CharacterReader",
      "org.jsoup.internal.StringUtil",
      "org.jsoup.internal.Normalizer",
      "org.jsoup.select.Evaluator",
      "org.jsoup.select.Evaluator$Tag",
      "org.jsoup.select.Evaluator$AttributeKeyPair",
      "org.jsoup.select.Evaluator$AttributeWithValue",
      "org.jsoup.select.CombiningEvaluator",
      "org.jsoup.select.CombiningEvaluator$And",
      "org.jsoup.select.Evaluator$Attribute",
      "org.jsoup.select.CombiningEvaluator$Or",
      "org.jsoup.helper.DataUtil",
      "org.jsoup.parser.Parser",
      "org.jsoup.parser.TreeBuilder",
      "org.jsoup.parser.HtmlTreeBuilder",
      "org.jsoup.parser.Token",
      "org.jsoup.parser.Token$Tag",
      "org.jsoup.parser.Token$EndTag",
      "org.jsoup.parser.Token$TokenType",
      "org.jsoup.parser.TokenData",
      "org.jsoup.parser.ParseSettings",
      "org.jsoup.parser.ParseErrorList",
      "org.jsoup.internal.SharedConstants",
      "org.jsoup.parser.Tag",
      "org.jsoup.parser.HtmlTagOptions",
      "org.jsoup.parser.TagSet",
      "org.jsoup.helper.HttpConnection$Response",
      "org.jsoup.helper.ValidationException",
      "org.jsoup.helper.HttpConnection",
      "org.jsoup.nodes.Node",
      "org.jsoup.nodes.Element$NodeList",
      "org.jsoup.nodes.Attributes",
      "org.jsoup.nodes.Element",
      "org.jsoup.nodes.Document",
      "org.jsoup.nodes.Document$OutputSettings",
      "org.jsoup.nodes.EntitiesData",
      "org.jsoup.nodes.Entities",
      "org.jsoup.nodes.Entities$EscapeMode",
      "org.jsoup.nodes.Document$QuirksMode",
      "org.jsoup.nodes.Attribute",
      "org.jsoup.nodes.Attributes$Dataset",
      "org.jsoup.helper.HttpConnection$KeyVal",
      "org.jsoup.nodes.NodeUtils",
      "org.jsoup.nodes.Attributes$Dataset$EntrySet",
      "org.jsoup.nodes.Attributes$Dataset$DatasetIterator",
      "org.jsoup.nodes.Attributes$1",
      "org.jsoup.parser.XmlTreeBuilder",
      "org.jsoup.helper.RequestExecutor",
      "org.jsoup.helper.UrlConnectionExecutor",
      "org.jsoup.nodes.LeafNode",
      "org.jsoup.nodes.TextNode",
      "org.jsoup.nodes.NodeIterator",
      "org.jsoup.parser.Tokeniser",
      "org.jsoup.parser.TokeniserState",
      "org.jsoup.parser.Token$Character",
      "org.jsoup.parser.Token$Doctype",
      "org.jsoup.parser.Token$Comment",
      "org.jsoup.parser.Token$StartTag",
      "org.jsoup.parser.Token$XmlDecl",
      "org.jsoup.parser.HtmlTreeBuilderState$7",
      "org.jsoup.parser.HtmlTreeBuilderState",
      "org.jsoup.parser.Token$EOF",
      "org.jsoup.parser.HtmlTreeBuilderState$25",
      "org.jsoup.parser.HtmlTreeBuilderState$Constants",
      "org.jsoup.select.Evaluator$ContainsWholeOwnText",
      "org.jsoup.select.Collector",
      "org.jsoup.internal.StringUtil$StringJoiner",
      "org.jsoup.select.Evaluator$Class",
      "org.jsoup.select.Selector$SelectorParseException",
      "org.jsoup.nodes.FormElement",
      "org.jsoup.nodes.CDataNode",
      "org.jsoup.internal.LineMap",
      "org.jsoup.nodes.NodeInternals",
      "org.jsoup.nodes.Range$Spans",
      "org.jsoup.nodes.Range$Position",
      "org.jsoup.nodes.Range",
      "org.jsoup.nodes.LeafNode$TrackedValue",
      "org.jsoup.select.Nodes",
      "org.jsoup.select.Elements",
      "org.jsoup.select.StructuralEvaluator",
      "org.jsoup.select.StructuralEvaluator$PreviousSibling",
      "org.jsoup.nodes.Comment",
      "org.jsoup.parser.XmlTreeBuilder$1",
      "org.jsoup.select.Evaluator$IsOnlyOfType",
      "org.jsoup.helper.UrlBuilder",
      "org.jsoup.select.Evaluator$IndexEvaluator",
      "org.jsoup.select.Evaluator$IndexLessThan",
      "org.jsoup.select.Evaluator$AttributeWithValueEnding",
      "org.jsoup.internal.QuietAppendable",
      "org.jsoup.internal.QuietAppendable$StringBuilderAppendable",
      "org.jsoup.nodes.Range$AttributeRange",
      "org.jsoup.nodes.Entities$CoreCharset",
      "org.jsoup.helper.W3CDom",
      "org.jsoup.helper.W3CDom$W3CBuilder",
      "org.jsoup.select.NodeTraversor",
      "org.jsoup.select.Evaluator$ContainsOwnText",
      "org.jsoup.select.Evaluator$AttributeWithValueContaining",
      "org.jsoup.select.NodeFilter$FilterResult",
      "org.jsoup.helper.Regex",
      "org.jsoup.helper.Re2jRegex",
      "com.google.re2j.Pattern",
      "com.google.re2j.RE2",
      "com.google.re2j.Parser",
      "com.google.re2j.Parser$Stack",
      "com.google.re2j.Parser$StringIterator",
      "com.google.re2j.Regexp$Op",
      "com.google.re2j.Regexp",
      "com.google.re2j.Simplify",
      "com.google.re2j.Simplify$1",
      "com.google.re2j.Compiler",
      "com.google.re2j.Prog",
      "com.google.re2j.Inst",
      "com.google.re2j.Compiler$Frag",
      "com.google.re2j.Compiler$1",
      "com.google.re2j.Unicode",
      "com.google.re2j.UnicodeTables",
      "com.google.re2j.Characters",
      "org.jsoup.select.Evaluator$Matches",
      "org.jsoup.nodes.Element$TextAccumulator",
      "org.jsoup.helper.Re2jRegex$Re2jMatcher",
      "com.google.re2j.Matcher",
      "com.google.re2j.MatcherInput",
      "com.google.re2j.MatcherInput$Utf16MatcherInput",
      "com.google.re2j.MatcherInput$Encoding",
      "com.google.re2j.MachineInput",
      "com.google.re2j.MachineInput$UTF16Input",
      "com.google.re2j.Machine",
      "com.google.re2j.Machine$Queue",
      "com.google.re2j.Utils",
      "org.jsoup.select.StructuralEvaluator$ImmediateParentRun",
      "org.jsoup.select.Evaluator$IndexGreaterThan",
      "org.jsoup.select.Evaluator$AttributeWithValueNot",
      "org.jsoup.select.StructuralEvaluator$Root",
      "org.jsoup.select.Evaluator$Id",
      "org.jsoup.nodes.DataNode",
      "org.jsoup.select.StructuralEvaluator$ImmediatePreviousSibling",
      "org.jsoup.select.Evaluator$ContainsText",
      "org.jsoup.Connection$Method"
    );
  }
}
