/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 20:45:31 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sun.org.apache.xerces.internal.dom.DocumentImpl;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.junit.runner.RunWith;
import org.w3c.dom.DOMException;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class W3CDom_ESTest extends W3CDom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Element element0 = new Element("DKfnEFV0hwP$");
      Document document0 = w3CDom0.fromJsoup(element0);
      // Undeclared exception!
      try { 
        w3CDom0.selectXpath("http://www.w3.org/XML/1998/namespace", (Node) document0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not evaluate XPath query [http://www.w3.org/XML/1998/namespace]: javax.xml.transform.TransformerException: A node test that matches either NCName:* or QName was expected.
         //
         verifyException("org.jsoup.helper.W3CDom", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = Parser.parseBodyFragment("javax.xml.xpath.XPathFactory:jsoup", "jsoupSource");
      org.jsoup.nodes.Document document1 = (org.jsoup.nodes.Document)document0.attr("javax.xml.xpath.XPathFactory:jsoup", true);
      DocumentImpl documentImpl0 = (DocumentImpl)w3CDom0.fromJsoup((Element) document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(documentImpl0);
      Parser parser0 = Parser.xmlParser();
      document1.parser(parser0);
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(document1, (-2788));
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      org.jsoup.nodes.Document document0 = Parser.parse("xmlns:", "jsoupSource");
      Document document1 = W3CDom.convert(document0);
      document0.attr("xmlns:", true);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(document0, 1592);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      assertTrue(w3CDom0.namespaceAware());
      
      W3CDom w3CDom1 = w3CDom0.namespaceAware(false);
      Element element0 = new Element("DKfnEFV0hwP$");
      Element element1 = element0.val("javax.xml.xpath.XPathFactory:jsoup");
      w3CDom1.fromJsoup(element1);
      assertFalse(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = Parser.parse("jsoupSource", "jsoupSource");
      Document document1 = w3CDom0.fromJsoup((Element) document0);
      Element element0 = document0.attr(".ir2k_SqD", true);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(element0, 1892);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Element element0 = new Element("DKfnEFV0hwP$");
      Element element1 = element0.val("javax.xml.xpath.XPathFactory:jsoup");
      w3CDom0.fromJsoup(element1);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = new org.jsoup.nodes.Document("http://www.w3.org/XML/1998/namespace", "javax.xml.xpath.XPathFactory:jsoup");
      document0.appendElement("http://www.w3.org/XML/1998/namespace");
      w3CDom0.fromJsoup(document0);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = new org.jsoup.nodes.Document("http://www.w3.org/XML/1998/namespace", "|KfnEFV0hwP$");
      document0.head();
      Document document1 = w3CDom0.fromJsoup(document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      Element element0 = document0.attr("http://www.w3.org/XML/1998/namespace", true);
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(element0, 222);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      org.jsoup.nodes.Document document0 = Parser.parseBodyFragment("jsoupSource", "javax.xml.xpath.XPathFactory:jsoup");
      Document document1 = W3CDom.convert(document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      DataNode dataNode0 = new DataNode("jsoupSource");
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(dataNode0, 782);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      org.jsoup.nodes.Document document0 = Parser.parseBodyFragment("jsoupSource", "javax.xml.xpath.XPathFactory:jsoup");
      Document document1 = W3CDom.convert(document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      w3CDom_W3CBuilder0.head((org.jsoup.nodes.Node) null, 23);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      assertTrue(w3CDom0.namespaceAware());
      
      W3CDom w3CDom1 = w3CDom0.namespaceAware(false);
      Element element0 = new Element("javax.xml.xpath.XPathFactory:jsoup");
      w3CDom1.fromJsoup(element0);
      assertFalse(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = org.jsoup.nodes.Document.createShell("jsoupSource");
      DocumentImpl documentImpl0 = (DocumentImpl)W3CDom.convert(document0);
      Class<Comment> class0 = Comment.class;
      w3CDom0.sourceNodes((NodeList) documentImpl0, class0);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = org.jsoup.nodes.Document.createShell("jsoupSource");
      DocumentImpl documentImpl0 = (DocumentImpl)w3CDom0.fromJsoup((Element) document0);
      Class<Element> class0 = Element.class;
      List<Element> list0 = w3CDom0.sourceNodes((NodeList) documentImpl0, class0);
      assertTrue(w3CDom0.namespaceAware());
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      org.jsoup.nodes.Document document0 = new org.jsoup.nodes.Document("jsoupSource");
      // Undeclared exception!
      try { 
        W3CDom.convert(document0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      org.jsoup.nodes.Document document0 = org.jsoup.nodes.Document.createShell("");
      Document document1 = W3CDom.convert(document0);
      assertNotNull(document1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Element element0 = new Element("DKfnEFV0hwP$");
      Document document0 = w3CDom0.fromJsoup(element0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document0);
      Comment comment0 = new Comment("NZ_c%WC:F=XTGjQ{6");
      w3CDom_W3CBuilder0.traverse(comment0);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = Parser.parseBodyFragment("jsoupSource", "J{D1twwQ");
      Document document1 = w3CDom0.fromJsoup((Element) document0);
      HashMap<String, String> hashMap0 = W3CDom.OutputHtml();
      String string0 = W3CDom.asString(document1, (Map<String, String>) hashMap0);
      assertEquals("<html xmlns=\"http://www.w3.org/1999/xhtml\"><head><META http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"></head><body>jsoupSource</body></html>", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      boolean boolean0 = w3CDom0.namespaceAware();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = org.jsoup.nodes.Document.createShell("jsoupSource");
      Document document1 = W3CDom.convert(document0);
      // Undeclared exception!
      try { 
        w3CDom0.convert(document0, document1);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMap<String, String> hashMap0 = W3CDom.OutputXml();
      assertFalse(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      // Undeclared exception!
      try { 
        w3CDom0.selectXpath("5H4t$/P?::i.WaL", (Document) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The parameter 'contextNode' must not be null.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      org.jsoup.nodes.Document document0 = Parser.parse("jsoupSource", "javax.xml.xpath.XPathFactory:jsoup");
      Elements elements0 = document0.selectXpath("jsoupSource");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      org.jsoup.nodes.Document document0 = Parser.parseBodyFragment("jsoupSource", "J{D1twwQ");
      Document document1 = w3CDom0.fromJsoup((Element) document0);
      w3CDom0.asString(document1);
  }
}
