/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 06:47:55 GMT 2026
 */

package com.itextpdf.text.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.itextpdf.text.io.ArrayRandomAccessSource;
import com.itextpdf.text.io.GetBufferedRandomAccessSource;
import com.itextpdf.text.io.GroupedRandomAccessSource;
import com.itextpdf.text.io.IndependentRandomAccessSource;
import com.itextpdf.text.io.RandomAccessSource;
import com.itextpdf.text.io.WindowRandomAccessSource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false)
public class GroupedRandomAccessSource_ESTest extends GroupedRandomAccessSource_ESTest_scaffolding {

    /**
     * Builds the 8-slot source array reused by many tests.
     *
     * Layout: [buffered, array, buffered, buffered, independent, buffered, array, independent]
     * where `buffered` wraps `base` and `independent` wraps `buffered`.
     */
    private RandomAccessSource[] buildEightSources(ArrayRandomAccessSource base) {
        GetBufferedRandomAccessSource buffered = new GetBufferedRandomAccessSource(base);
        IndependentRandomAccessSource independent = new IndependentRandomAccessSource(buffered);
        RandomAccessSource[] sources = new RandomAccessSource[8];
        sources[0] = (RandomAccessSource) buffered;
        sources[1] = (RandomAccessSource) base;
        sources[2] = (RandomAccessSource) buffered;
        sources[3] = (RandomAccessSource) buffered;
        sources[4] = (RandomAccessSource) independent;
        sources[5] = (RandomAccessSource) buffered;
        sources[6] = (RandomAccessSource) base;
        sources[7] = (RandomAccessSource) independent;
        return sources;
    }

    @Test(timeout = 4000)
    public void testLengthAfterClose_returnsAggregatedLength() throws Throwable {
        // GroupedRandomAccessSource reports the total length even after close().
        byte[] data = new byte[6];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = buildEightSources(base);
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        grouped.close();
        assertEquals(48L, grouped.length()); // 8 sources × 6 bytes = 48
    }

    @Test(timeout = 4000)
    public void testGetBulk_positionBeforeWindowStart_returnsMinusOne() throws Throwable {
        // A WindowRandomAccessSource with offset 807 has no data before that position.
        // Requesting bytes at position 196 (before the window) returns -1.
        byte[] dest = new byte[6];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(dest);
        WindowRandomAccessSource window = new WindowRandomAccessSource(base, 807L, 807L);
        RandomAccessSource[] sources = new RandomAccessSource[1];
        sources[0] = (RandomAccessSource) window;
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int bytesRead = grouped.get(196L, dest, 1318, 1318);
        assertEquals((-1), bytesRead);
        assertEquals(807L, grouped.length());
    }

    @Test(timeout = 4000)
    public void testGetBulk_negativeBufferOffsetAndLength_returnsMinusOne() throws Throwable {
        // Passing a negative buffer offset and negative length to get() returns -1.
        byte[] data = new byte[8];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = buildEightSources(base);
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int bytesRead = grouped.get((long) (byte)0, data, (int) (byte) (-126), (int) (byte) (-43));
        assertEquals((-1), bytesRead);
        assertEquals(64L, grouped.length()); // 8 sources × 8 bytes = 64
    }

    @Test(timeout = 4000)
    public void testGetSingle_negativePosition_returnsMinusOne() throws Throwable {
        // Reading a single byte at a negative position returns -1.
        byte[] data = new byte[8];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = buildEightSources(base);
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int result = grouped.get((-1L));
        assertEquals(64L, grouped.length());
        assertEquals((-1), result);
    }

    @Test(timeout = 4000)
    public void testGetSingle_positionZero_returnsZeroByte() throws Throwable {
        // Reading a single byte at position 0 from a zero-filled source returns 0.
        byte[] data = new byte[7];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = buildEightSources(base);
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int result = grouped.get(0L);
        assertEquals(56L, grouped.length()); // 8 sources × 7 bytes = 56
        assertEquals(0, result);
    }

    @Test(timeout = 4000)
    public void testGetBulk_negativePosition_returnsMinusOne() throws Throwable {
        // Reading bytes starting at position -1 returns -1.
        byte[] data = new byte[6];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = buildEightSources(base);
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int bytesRead = grouped.get((long) (-1), data, 1310, (-156));
        assertEquals(48L, grouped.length()); // 8 sources × 6 bytes = 48
        assertEquals((-1), bytesRead);
    }

    @Test(timeout = 4000)
    public void testGetBulk_readBeyondEnd_returnsAvailableByteCount() throws Throwable {
        // Requesting 4 bytes starting at position 4 in a 6-byte source returns 2 (only 2 remain).
        byte[] data = new byte[6];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = new RandomAccessSource[1];
        sources[0] = (RandomAccessSource) base;
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        int bytesRead = grouped.get((long) 4, data, 4, 4);
        assertEquals(6L, grouped.length());
        assertEquals(2, bytesRead);
    }

    @Test(timeout = 4000)
    public void testLength_windowWithNegativeLength_returnsNegativeLength() throws Throwable {
        // A WindowRandomAccessSource constructed with a negative length reports that negative value.
        WindowRandomAccessSource window = new WindowRandomAccessSource((RandomAccessSource) null, (-2147L), (-645L));
        RandomAccessSource[] sources = new RandomAccessSource[1];
        sources[0] = (RandomAccessSource) window;
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        long length = grouped.length();
        assertEquals((-645L), length);
    }

    @Test(timeout = 4000)
    public void testGetBulk_readSpansPastArrayEnd_throwsArrayIndexOutOfBounds() throws Throwable {
        // Reading 5 bytes starting at position 5 into a 6-element destination array causes
        // ArrayIndexOutOfBoundsException because the copy would write past index 5.
        byte[] data = new byte[6];
        ArrayRandomAccessSource base = new ArrayRandomAccessSource(data);
        RandomAccessSource[] sources = new RandomAccessSource[2];
        sources[0] = (RandomAccessSource) base;
        sources[1] = (RandomAccessSource) base;
        GroupedRandomAccessSource grouped = new GroupedRandomAccessSource(sources);
        try {
            grouped.get((long) 5, data, 5, 5);
            fail("Expecting exception: ArrayIndexOutOfBoundsException");
        } catch(ArrayIndexOutOfBoundsException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("com.itextpdf.text.io.ArrayRandomAccessSource", e);
        }
    }
}
