/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 05:18:04 GMT 2026
 */

package org.apache.commons.collections4.comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.util.LinkedList;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.comparators.FixedOrderComparator;
import org.apache.commons.collections4.functors.EqualPredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FixedOrderComparator_ESTest extends FixedOrderComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Predicate<Object>> linkedList0 = new LinkedList<Predicate<Object>>();
      FixedOrderComparator<Predicate<Object>> fixedOrderComparator0 = new FixedOrderComparator<Predicate<Object>>(linkedList0);
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>();
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      boolean boolean0 = fixedOrderComparator0.equals(fixedOrderComparator1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(linkedList0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      Object[] objectArray0 = new Object[9];
      objectArray0[4] = (Object) fixedOrderComparator0;
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator<Object> fixedOrderComparator2 = new FixedOrderComparator<Object>(objectArray0);
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>(fixedOrderComparator2);
      fixedOrderComparator0.compare(equalPredicate0, objectArray0[1]);
      FixedOrderComparator<Object>[] fixedOrderComparatorArray0 = (FixedOrderComparator<Object>[]) Array.newInstance(FixedOrderComparator.class, 5);
      fixedOrderComparatorArray0[0] = fixedOrderComparator1;
      fixedOrderComparatorArray0[4] = fixedOrderComparator2;
      FixedOrderComparator<FixedOrderComparator<Object>> fixedOrderComparator3 = new FixedOrderComparator<FixedOrderComparator<Object>>(fixedOrderComparatorArray0);
      assertEquals(FixedOrderComparator.UnknownObjectBehavior.EXCEPTION, fixedOrderComparator3.getUnknownObjectBehavior());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FixedOrderComparator<Predicate<Object>> fixedOrderComparator0 = new FixedOrderComparator<Predicate<Object>>();
      Object[] objectArray0 = new Object[0];
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      Object object0 = new Object();
      fixedOrderComparator1.compare(fixedOrderComparator0, object0);
      boolean boolean0 = fixedOrderComparator0.equals(fixedOrderComparator1);
      assertTrue(fixedOrderComparator1.isLocked());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FixedOrderComparator.UnknownObjectBehavior[] fixedOrderComparator_UnknownObjectBehaviorArray0 = FixedOrderComparator.UnknownObjectBehavior.values();
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(fixedOrderComparator_UnknownObjectBehaviorArray0);
      FixedOrderComparator<Predicate<Object>> fixedOrderComparator1 = new FixedOrderComparator<Predicate<Object>>();
      boolean boolean0 = fixedOrderComparator1.equals(fixedOrderComparator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      Object object0 = new Object();
      boolean boolean0 = fixedOrderComparator0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<FixedOrderComparator.UnknownObjectBehavior> linkedList0 = new LinkedList<FixedOrderComparator.UnknownObjectBehavior>();
      FixedOrderComparator<FixedOrderComparator.UnknownObjectBehavior> fixedOrderComparator0 = new FixedOrderComparator<FixedOrderComparator.UnknownObjectBehavior>(linkedList0);
      boolean boolean0 = fixedOrderComparator0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      boolean boolean0 = fixedOrderComparator0.equals(fixedOrderComparator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FixedOrderComparator<Predicate<Object>> fixedOrderComparator0 = new FixedOrderComparator<Predicate<Object>>();
      Object[] objectArray0 = new Object[5];
      objectArray0[1] = (Object) fixedOrderComparator0;
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      FixedOrderComparator<Object> fixedOrderComparator2 = new FixedOrderComparator<Object>();
      int int0 = fixedOrderComparator1.compare(fixedOrderComparator1, fixedOrderComparator2);
      assertTrue(fixedOrderComparator1.isLocked());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(linkedList0);
      fixedOrderComparator0.add(fixedOrderComparator1);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.AFTER;
      fixedOrderComparator0.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator0.compare(fixedOrderComparator1, fixedOrderComparator0);
      assertTrue(fixedOrderComparator0.isLocked());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      Object[] objectArray0 = new Object[1];
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(objectArray0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator1.compare(objectArray0[0], fixedOrderComparator0);
      assertTrue(fixedOrderComparator1.isLocked());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(linkedList0);
      fixedOrderComparator0.add(fixedOrderComparator1);
      // Undeclared exception!
      try { 
        fixedOrderComparator0.compare(fixedOrderComparator1, fixedOrderComparator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object org.apache.commons.collections4.comparators.FixedOrderComparator@a6979fb9
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      Object[] objectArray0 = new Object[2];
      objectArray0[1] = (Object) fixedOrderComparator0;
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(objectArray0);
      fixedOrderComparator1.compare(objectArray0[0], fixedOrderComparator0);
      // Undeclared exception!
      try { 
        fixedOrderComparator1.checkLocked();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Cannot modify a FixedOrderComparator after a comparison
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Object[] objectArray0 = new Object[5];
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>(objectArray0);
      boolean boolean0 = fixedOrderComparator0.addAsEqual(objectArray0[3], objectArray0[3]);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object[] objectArray0 = new Object[5];
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      // Undeclared exception!
      try { 
        fixedOrderComparator0.addAsEqual(objectArray0[3], fixedOrderComparator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // null not known to org.apache.commons.collections4.comparators.FixedOrderComparator@7d34ba0f
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      Object object0 = new Object();
      boolean boolean0 = fixedOrderComparator0.add((Object) null);
      boolean boolean1 = fixedOrderComparator0.addAsEqual((Object) null, object0);
      assertTrue(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) fixedOrderComparator0);
      FixedOrderComparator<Object> fixedOrderComparator1 = new FixedOrderComparator<Object>(linkedList0);
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = FixedOrderComparator.UnknownObjectBehavior.BEFORE;
      fixedOrderComparator1.setUnknownObjectBehavior(fixedOrderComparator_UnknownObjectBehavior0);
      int int0 = fixedOrderComparator1.compare(linkedList0, fixedOrderComparator0);
      assertTrue(fixedOrderComparator1.isLocked());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FixedOrderComparator<FixedOrderComparator.UnknownObjectBehavior> fixedOrderComparator0 = new FixedOrderComparator<FixedOrderComparator.UnknownObjectBehavior>();
      FixedOrderComparator.UnknownObjectBehavior fixedOrderComparator_UnknownObjectBehavior0 = fixedOrderComparator0.getUnknownObjectBehavior();
      assertEquals(FixedOrderComparator.UnknownObjectBehavior.EXCEPTION, fixedOrderComparator_UnknownObjectBehavior0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FixedOrderComparator<Object> fixedOrderComparator0 = new FixedOrderComparator<Object>();
      // Undeclared exception!
      try { 
        fixedOrderComparator0.compare(fixedOrderComparator0, fixedOrderComparator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Attempting to compare unknown object org.apache.commons.collections4.comparators.FixedOrderComparator@7d34a389
         //
         verifyException("org.apache.commons.collections4.comparators.FixedOrderComparator", e);
      }
  }
}
