/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jun 15 14:29:50 GMT 2026
 */

package org.apache.commons.math4.legacy.analysis.function;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class Gaussian_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.math4.legacy.analysis.function.Gaussian"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/tenghaha/Projects/New_Agent_understandability_improvement/scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/y7/5v6zwzln5s14jn6cndl4lq7m0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Gaussian_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.math4.legacy.exception.util.Localizable",
      "org.apache.commons.math4.legacy.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.legacy.analysis.differentiation.DerivativeStructure",
      "org.apache.commons.math4.legacy.exception.NonMonotonicSequenceException",
      "org.apache.commons.math4.legacy.exception.NullArgumentException",
      "org.apache.commons.math4.legacy.exception.util.ExceptionContext",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$Split",
      "org.apache.commons.numbers.core.Precision$DoubleEquivalence",
      "org.apache.commons.math4.legacy.exception.NumberIsTooLargeException",
      "org.apache.commons.math4.core.jdkmath.JdkMath$FloatUnaryOperator",
      "org.apache.commons.math4.core.jdkmath.JdkMath$DoubleInt2DoubleOperator",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$ExpFracTable",
      "org.apache.commons.math4.core.jdkmath.JdkMath",
      "org.apache.commons.math4.legacy.analysis.ParametricUnivariateFunction",
      "org.apache.commons.math4.core.jdkmath.JdkMath$FloatInt2FloatOperator",
      "org.apache.commons.math4.legacy.exception.NotFiniteNumberException",
      "org.apache.commons.math4.legacy.core.MathArrays",
      "org.apache.commons.math4.legacy.exception.MathIllegalNumberException",
      "org.apache.commons.math4.legacy.exception.NoDataException",
      "org.apache.commons.math4.legacy.core.Field",
      "org.apache.commons.math4.legacy.analysis.differentiation.DSCompiler",
      "org.apache.commons.math4.core.jdkmath.AccurateMath",
      "org.apache.commons.math4.legacy.exception.MathIllegalStateException",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$ExpIntTable",
      "org.apache.commons.math4.legacy.exception.util.ArgUtils",
      "org.apache.commons.math4.legacy.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.legacy.exception.DimensionMismatchException",
      "org.apache.commons.math4.legacy.core.RealFieldElement",
      "org.apache.commons.math4.core.jdkmath.AccurateMathLiteralArrays",
      "org.apache.commons.math4.legacy.exception.MathRuntimeException",
      "org.apache.commons.math4.legacy.analysis.UnivariateFunction",
      "org.apache.commons.math4.core.jdkmath.JdkMath$FloatToIntFunction",
      "org.apache.commons.numbers.core.Precision",
      "org.apache.commons.math4.legacy.analysis.differentiation.UnivariateDifferentiableFunction",
      "org.apache.commons.math4.legacy.analysis.function.Gaussian",
      "org.apache.commons.math4.legacy.exception.util.ExceptionContextProvider",
      "org.apache.commons.math4.legacy.exception.MathArithmeticException",
      "org.apache.commons.math4.legacy.exception.util.LocalizedFormats",
      "org.apache.commons.math4.legacy.exception.NotStrictlyPositiveException",
      "org.apache.commons.math4.legacy.exception.NotANumberException",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$lnMant",
      "org.apache.commons.math4.legacy.core.FieldElement",
      "org.apache.commons.math4.legacy.exception.MathInternalError",
      "org.apache.commons.math4.legacy.analysis.function.Gaussian$Parametric",
      "org.apache.commons.math4.core.jdkmath.JdkMath$FloatDouble2FloatOperator",
      "org.apache.commons.math4.legacy.exception.NotPositiveException",
      "org.apache.commons.math4.core.jdkmath.JdkMath$Impl",
      "org.apache.commons.math4.core.jdkmath.JdkMath$FloatBinaryOperator"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Gaussian_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.math4.legacy.analysis.function.Gaussian",
      "org.apache.commons.math4.core.jdkmath.JdkMath$Impl",
      "org.apache.commons.math4.core.jdkmath.JdkMath",
      "org.apache.commons.math4.legacy.exception.MathRuntimeException",
      "org.apache.commons.math4.legacy.exception.MathIllegalArgumentException",
      "org.apache.commons.math4.legacy.exception.MathIllegalNumberException",
      "org.apache.commons.math4.legacy.exception.NumberIsTooSmallException",
      "org.apache.commons.math4.legacy.exception.NotStrictlyPositiveException",
      "org.apache.commons.math4.legacy.exception.util.LocalizedFormats",
      "org.apache.commons.math4.legacy.exception.util.ExceptionContext",
      "org.apache.commons.math4.legacy.exception.util.ArgUtils",
      "org.apache.commons.math4.legacy.analysis.function.Gaussian$Parametric",
      "org.apache.commons.math4.legacy.exception.DimensionMismatchException",
      "org.apache.commons.math4.core.jdkmath.AccurateMath",
      "org.apache.commons.math4.core.jdkmath.AccurateMathLiteralArrays",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$ExpIntTable",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$ExpFracTable",
      "org.apache.commons.math4.legacy.analysis.differentiation.DerivativeStructure",
      "org.apache.commons.math4.legacy.analysis.differentiation.DSCompiler",
      "org.apache.commons.math4.legacy.exception.NullArgumentException",
      "org.apache.commons.numbers.angle.Reduce",
      "org.apache.commons.math4.legacy.exception.NumberIsTooLargeException",
      "org.apache.commons.numbers.core.Sum",
      "org.apache.commons.numbers.core.ExtendedPrecision",
      "org.apache.commons.numbers.core.DD",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$Split",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$lnMant",
      "org.apache.commons.math4.core.jdkmath.AccurateMath$CodyWaite",
      "org.apache.commons.math4.legacy.core.MathArrays",
      "org.apache.commons.numbers.core.Precision"
    );
  }
}
