/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 07:10:36 GMT 2026
 */

package com.itextpdf.text.pdf.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.itextpdf.awt.geom.Rectangle2D;
import com.itextpdf.text.pdf.parser.ImageRenderInfo;
import com.itextpdf.text.pdf.parser.LocationTextExtractionStrategy;
import com.itextpdf.text.pdf.parser.MultiFilteredRenderListener;
import com.itextpdf.text.pdf.parser.RegionTextRenderFilter;
import com.itextpdf.text.pdf.parser.RenderFilter;
import com.itextpdf.text.pdf.parser.TextRenderInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class MultiFilteredRenderListener_ESTest extends MultiFilteredRenderListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      LocationTextExtractionStrategy locationTextExtractionStrategy0 = new LocationTextExtractionStrategy();
      RenderFilter[] renderFilterArray0 = new RenderFilter[1];
      Rectangle2D.Double rectangle2D_Double0 = new Rectangle2D.Double((-1942.12867043), (-1942.12867043), (-1942.12867043), 698.1615839);
      RegionTextRenderFilter regionTextRenderFilter0 = new RegionTextRenderFilter(rectangle2D_Double0);
      renderFilterArray0[0] = (RenderFilter) regionTextRenderFilter0;
      multiFilteredRenderListener0.attachRenderListener(locationTextExtractionStrategy0, renderFilterArray0);
      multiFilteredRenderListener0.renderImage((ImageRenderInfo) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      LocationTextExtractionStrategy locationTextExtractionStrategy0 = new LocationTextExtractionStrategy();
      RenderFilter[] renderFilterArray0 = new RenderFilter[0];
      multiFilteredRenderListener0.attachRenderListener(locationTextExtractionStrategy0, renderFilterArray0);
      multiFilteredRenderListener0.endTextBlock();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      LocationTextExtractionStrategy locationTextExtractionStrategy0 = new LocationTextExtractionStrategy();
      RenderFilter[] renderFilterArray0 = new RenderFilter[1];
      multiFilteredRenderListener0.attachRenderListener(locationTextExtractionStrategy0, renderFilterArray0);
      // Undeclared exception!
      try { 
        multiFilteredRenderListener0.renderText((TextRenderInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.itextpdf.text.pdf.parser.MultiFilteredRenderListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      LocationTextExtractionStrategy locationTextExtractionStrategy0 = new LocationTextExtractionStrategy();
      RenderFilter[] renderFilterArray0 = new RenderFilter[0];
      multiFilteredRenderListener0.attachRenderListener(locationTextExtractionStrategy0, renderFilterArray0);
      // Undeclared exception!
      try { 
        multiFilteredRenderListener0.renderText((TextRenderInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.itextpdf.text.pdf.parser.LocationTextExtractionStrategy", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      multiFilteredRenderListener0.renderText((TextRenderInfo) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      multiFilteredRenderListener0.beginTextBlock();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MultiFilteredRenderListener multiFilteredRenderListener0 = new MultiFilteredRenderListener();
      LocationTextExtractionStrategy locationTextExtractionStrategy0 = new LocationTextExtractionStrategy();
      RenderFilter[] renderFilterArray0 = new RenderFilter[0];
      multiFilteredRenderListener0.attachRenderListener(locationTextExtractionStrategy0, renderFilterArray0);
      multiFilteredRenderListener0.beginTextBlock();
  }
}
