/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 05:28:56 GMT 2026
 */

package org.apache.commons.collections4.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.sql.ClientInfoStatus;
import java.sql.SQLNonTransientConnectionException;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.TreeSet;
import org.apache.commons.collections4.iterators.CartesianProductIterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class CartesianProductIterator_ESTest extends CartesianProductIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<ClientInfoStatus> class0 = ClientInfoStatus.class;
      EnumSet<ClientInfoStatus> enumSet0 = EnumSet.allOf(class0);
      Iterable<ClientInfoStatus>[] iterableArray0 = (Iterable<ClientInfoStatus>[]) Array.newInstance(Iterable.class, 3);
      iterableArray0[0] = (Iterable<ClientInfoStatus>) enumSet0;
      iterableArray0[1] = (Iterable<ClientInfoStatus>) enumSet0;
      ClientInfoStatus clientInfoStatus0 = ClientInfoStatus.REASON_UNKNOWN_PROPERTY;
      EnumSet<ClientInfoStatus> enumSet1 = EnumSet.of(clientInfoStatus0);
      iterableArray0[2] = (Iterable<ClientInfoStatus>) enumSet1;
      CartesianProductIterator<Object> cartesianProductIterator0 = new CartesianProductIterator<Object>(iterableArray0);
      List<Object> list0 = cartesianProductIterator0.next();
      assertFalse(list0.isEmpty());
      
      List<Object> list1 = cartesianProductIterator0.next();
      assertFalse(list1.equals((Object)list0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Iterable<Object>[] iterableArray0 = (Iterable<Object>[]) Array.newInstance(Iterable.class, 0);
      CartesianProductIterator<Object> cartesianProductIterator0 = new CartesianProductIterator<Object>(iterableArray0);
      // Undeclared exception!
      try { 
        cartesianProductIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.iterators.CartesianProductIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Iterable<SQLNonTransientConnectionException>[] iterableArray0 = (Iterable<SQLNonTransientConnectionException>[]) Array.newInstance(Iterable.class, 4);
      Comparator<SQLNonTransientConnectionException> comparator0 = (Comparator<SQLNonTransientConnectionException>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeSet<SQLNonTransientConnectionException> treeSet0 = new TreeSet<SQLNonTransientConnectionException>(comparator0);
      iterableArray0[0] = (Iterable<SQLNonTransientConnectionException>) treeSet0;
      CartesianProductIterator<SQLNonTransientConnectionException> cartesianProductIterator0 = new CartesianProductIterator<SQLNonTransientConnectionException>(iterableArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Iterable<Object>[] iterableArray0 = (Iterable<Object>[]) Array.newInstance(Iterable.class, 0);
      CartesianProductIterator<Object> cartesianProductIterator0 = new CartesianProductIterator<Object>(iterableArray0);
      // Undeclared exception!
      try { 
        cartesianProductIterator0.remove();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // remove
         //
         verifyException("org.apache.commons.collections4.iterators.CartesianProductIterator", e);
      }
  }
}
