/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 05:11:17 GMT 2026
 */

package org.apache.commons.collections4.comparators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteBuffer;
import java.util.BitSet;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Function;
import java.util.function.ToIntFunction;
import java.util.function.ToLongFunction;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.comparators.ComparatorChain;
import org.apache.commons.collections4.functors.ComparatorPredicate;
import org.apache.commons.collections4.functors.ExceptionTransformer;
import org.apache.commons.collections4.functors.InstanceofPredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class ComparatorChain_ESTest extends ComparatorChain_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Transformer<Comparable<ByteBuffer>, ByteBuffer> transformer0 = ExceptionTransformer.exceptionTransformer();
      Comparator<ByteBuffer> comparator0 = Comparator.comparing((Function<? super ByteBuffer, ? extends ByteBuffer>) transformer0);
      ComparatorChain<ByteBuffer> comparatorChain0 = new ComparatorChain<ByteBuffer>(comparator0, true);
      comparatorChain0.setComparator(0, comparator0, true);
      assertFalse(comparatorChain0.isLocked());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ComparatorChain<ComparatorChain<Object>> comparatorChain0 = new ComparatorChain<ComparatorChain<Object>>();
      ComparatorChain<ComparatorChain<Object>> comparatorChain1 = new ComparatorChain<ComparatorChain<Object>>(comparatorChain0);
      comparatorChain1.setComparator(0, (Comparator<ComparatorChain<Object>>) comparatorChain0);
      assertFalse(comparatorChain0.isLocked());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0, (BitSet) null);
      comparatorChain0.hashCode();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ComparatorChain<InstanceofPredicate> comparatorChain0 = new ComparatorChain<InstanceofPredicate>();
      comparatorChain0.hashCode();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      BitSet bitSet0 = BitSet.valueOf(byteArray0);
      ComparatorChain<ComparatorPredicate.Criterion> comparatorChain0 = new ComparatorChain<ComparatorPredicate.Criterion>((List<Comparator<ComparatorPredicate.Criterion>>) null, bitSet0);
      comparatorChain0.hashCode();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Comparator<ComparatorChain<Object>>> linkedList0 = new LinkedList<Comparator<ComparatorChain<Object>>>();
      ComparatorChain<ComparatorChain<Object>> comparatorChain0 = new ComparatorChain<ComparatorChain<Object>>(linkedList0);
      ToLongFunction<Object> toLongFunction0 = (ToLongFunction<Object>) mock(ToLongFunction.class, new ViolatedAssumptionAnswer());
      Comparator<ComparatorChain<Boolean>> comparator0 = Comparator.comparingLong((ToLongFunction<? super ComparatorChain<Boolean>>) toLongFunction0);
      ComparatorChain<ComparatorChain<Boolean>> comparatorChain1 = new ComparatorChain<ComparatorChain<Boolean>>(comparator0, false);
      boolean boolean0 = comparatorChain1.equals(comparatorChain0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ComparatorChain<InstanceofPredicate> comparatorChain0 = new ComparatorChain<InstanceofPredicate>();
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain1 = new ComparatorChain<Object>(linkedList0);
      Comparator<Integer> comparator0 = Comparator.nullsFirst((Comparator<? super Integer>) comparatorChain1);
      ComparatorChain<Integer> comparatorChain2 = new ComparatorChain<Integer>(comparator0, true);
      boolean boolean0 = comparatorChain0.equals(comparatorChain2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ComparatorChain<InstanceofPredicate> comparatorChain0 = new ComparatorChain<InstanceofPredicate>();
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      boolean boolean0 = comparatorChain0.equals(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>();
      boolean boolean0 = comparatorChain0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ToIntFunction<Object> toIntFunction0 = (ToIntFunction<Object>) mock(ToIntFunction.class, new ViolatedAssumptionAnswer());
      Comparator<Boolean> comparator0 = Comparator.comparingInt((ToIntFunction<? super Boolean>) toIntFunction0);
      ComparatorChain<Boolean> comparatorChain0 = new ComparatorChain<Boolean>(comparator0);
      boolean boolean0 = comparatorChain0.equals(comparatorChain0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ComparatorChain<InstanceofPredicate> comparatorChain0 = new ComparatorChain<InstanceofPredicate>();
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain1 = new ComparatorChain<Object>(linkedList0);
      boolean boolean0 = comparatorChain1.equals(comparatorChain0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0);
      Comparator<Object> comparator0 = Comparator.nullsLast((Comparator<? super Object>) comparatorChain0);
      comparatorChain0.addComparator(comparator0, true);
      int int0 = comparatorChain0.compare((Object) null, linkedList0);
      assertTrue(comparatorChain0.isLocked());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0);
      Comparator<Object> comparator0 = Comparator.nullsLast((Comparator<? super Object>) comparatorChain0);
      comparatorChain0.addComparator(comparator0, true);
      int int0 = comparatorChain0.compare(comparatorChain0, (Object) null);
      assertTrue(comparatorChain0.isLocked());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<Comparator<Comparator<ByteBuffer>>> linkedList0 = new LinkedList<Comparator<Comparator<ByteBuffer>>>();
      Comparator<Object> comparator0 = Comparator.nullsLast((Comparator<? super Object>) null);
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(comparator0);
      int int0 = comparatorChain0.compare(linkedList0, linkedList0);
      assertTrue(comparatorChain0.isLocked());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0);
      Comparator<Object> comparator0 = Comparator.nullsLast((Comparator<? super Object>) comparatorChain0);
      comparatorChain0.addComparator(comparator0, false);
      comparatorChain0.compare(comparatorChain0, (Object) null);
      // Undeclared exception!
      try { 
        comparatorChain0.setComparator((-1), (Comparator<Object>) comparatorChain0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Comparator ordering cannot be changed after the first comparison is performed
         //
         verifyException("org.apache.commons.collections4.comparators.ComparatorChain", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>();
      try { 
        comparatorChain0.compare(comparatorChain0, comparatorChain0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // ComparatorChains must contain at least one Comparator
         //
         verifyException("org.apache.commons.collections4.comparators.ComparatorChain", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0);
      comparatorChain0.addComparator((Comparator<Object>) comparatorChain0, true);
      // Undeclared exception!
      try { 
        comparatorChain0.compare(comparatorChain0, (Object) null);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ComparatorChain<Transformer<InstanceofPredicate, Object>> comparatorChain0 = new ComparatorChain<Transformer<InstanceofPredicate, Object>>();
      comparatorChain0.setForwardSort(0);
      assertFalse(comparatorChain0.isLocked());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<Comparator<Object>> linkedList0 = new LinkedList<Comparator<Object>>();
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>(linkedList0);
      comparatorChain0.addComparator((Comparator<Object>) comparatorChain0);
      assertEquals(1, comparatorChain0.size());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Comparator<InstanceofPredicate>> linkedList0 = new LinkedList<Comparator<InstanceofPredicate>>();
      BitSet bitSet0 = new BitSet();
      ComparatorChain<InstanceofPredicate> comparatorChain0 = new ComparatorChain<InstanceofPredicate>(linkedList0, bitSet0);
      int int0 = comparatorChain0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ComparatorChain<ComparatorChain<ByteBuffer>> comparatorChain0 = new ComparatorChain<ComparatorChain<ByteBuffer>>();
      comparatorChain0.setReverseSort(2147483645);
      assertEquals(0, comparatorChain0.size());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ComparatorChain<Object> comparatorChain0 = new ComparatorChain<Object>();
      boolean boolean0 = comparatorChain0.isLocked();
      assertFalse(boolean0);
  }
}
