/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 06:45:03 GMT 2026
 */

package org.apache.commons.collections4.bloomfilter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Comparator;
import java.util.Deque;
import java.util.NoSuchElementException;
import java.util.function.Consumer;
import org.apache.commons.collections4.Factory;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.bloomfilter.BloomFilter;
import org.apache.commons.collections4.bloomfilter.LayerManager;
import org.apache.commons.collections4.bloomfilter.Shape;
import org.apache.commons.collections4.bloomfilter.SimpleBloomFilter;
import org.apache.commons.collections4.bloomfilter.SparseBloomFilter;
import org.apache.commons.collections4.functors.AndPredicate;
import org.apache.commons.collections4.functors.ComparatorPredicate;
import org.apache.commons.collections4.functors.ConstantFactory;
import org.apache.commons.collections4.functors.IdentityPredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class LayerManager_ESTest extends LayerManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0).when(comparator0).compare(any() , any());
      Predicate<Object> predicate0 = ComparatorPredicate.comparatorPredicate((Object) layerManager_Builder0, comparator0);
      AndPredicate<LayerManager<SparseBloomFilter>> andPredicate0 = new AndPredicate<LayerManager<SparseBloomFilter>>(predicate0, predicate0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setExtendCheck(andPredicate0);
      Shape shape0 = Shape.fromKM(3888, 3888);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      Factory<SparseBloomFilter> factory0 = ConstantFactory.constantFactory(sparseBloomFilter0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder2 = layerManager_Builder1.setSupplier(factory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder2.get();
      layerManager0.getTarget();
      assertEquals(2, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      // Undeclared exception!
      try { 
        layerManager0.get(902);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Depth must be in the range [0,1)
         //
         verifyException("org.apache.commons.collections4.bloomfilter.LayerManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromKM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      SparseBloomFilter sparseBloomFilter1 = layerManager0.get(0);
      assertSame(sparseBloomFilter1, sparseBloomFilter0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      // Undeclared exception!
      try { 
        layerManager0.get((-1));
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Depth must be in the range [0,1)
         //
         verifyException("org.apache.commons.collections4.bloomfilter.LayerManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromKM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      layerManager0.cleanup();
      assertEquals(1, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromKM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      LayerManager<SparseBloomFilter> layerManager1 = layerManager0.copy();
      assertEquals(1, layerManager1.getDepth());
      assertNotSame(layerManager1, layerManager0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        LayerManager.ExtendCheck.advanceOnSaturation((-802.4096917680027));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 'maxN' must be greater than 0
         //
         verifyException("org.apache.commons.collections4.bloomfilter.LayerManager$ExtendCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      java.util.function.Predicate<LayerManager<SparseBloomFilter>> predicate0 = LayerManager.ExtendCheck.advanceOnSaturation(2.147483647E9);
      assertNotNull(predicate0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        LayerManager.ExtendCheck.advanceOnCount((-1090));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 'breakAt' must be greater than 0
         //
         verifyException("org.apache.commons.collections4.bloomfilter.LayerManager$ExtendCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(2537, 2537);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      Consumer<Deque<SparseBloomFilter>> consumer0 = LayerManager.Cleanup.removeEmptyTarget();
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setCleanup(consumer0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder1.get();
      layerManager0.cleanup();
      assertEquals(1, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setSupplier(constantFactory0);
      Consumer<Deque<SparseBloomFilter>> consumer0 = LayerManager.Cleanup.onMaxSize(902);
      layerManager_Builder0.setCleanup(consumer0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder1.get();
      layerManager0.next();
      assertEquals(2, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        LayerManager.Cleanup.onMaxSize((-2114));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 'maxSize' must be greater than 0
         //
         verifyException("org.apache.commons.collections4.bloomfilter.LayerManager$Cleanup", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      java.util.function.Predicate<LayerManager<SimpleBloomFilter>> predicate0 = LayerManager.ExtendCheck.advanceOnCount(967);
      assertNotNull(predicate0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IdentityPredicate<Object> identityPredicate0 = new IdentityPredicate<Object>((Object) null);
      Consumer<Deque<SimpleBloomFilter>> consumer0 = LayerManager.Cleanup.removeIf((java.util.function.Predicate<? super SimpleBloomFilter>) identityPredicate0);
      assertNotNull(consumer0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      java.util.function.Predicate<LayerManager<SparseBloomFilter>> predicate0 = LayerManager.ExtendCheck.advanceOnPopulated();
      assertNotNull(predicate0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      SparseBloomFilter sparseBloomFilter1 = layerManager0.first();
      assertEquals(1, sparseBloomFilter1.characteristics());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(62119, 62119);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      Factory<SparseBloomFilter> factory0 = ConstantFactory.constantFactory(sparseBloomFilter0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setSupplier(factory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder1.get();
      int int0 = layerManager0.getDepth();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder1.get();
      layerManager0.clear();
      assertEquals(1, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(902, 902);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder0.get();
      layerManager0.getTarget();
      assertEquals(1, layerManager0.getDepth());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder0 = LayerManager.builder();
      Shape shape0 = Shape.fromNM(904, 904);
      SparseBloomFilter sparseBloomFilter0 = new SparseBloomFilter(shape0);
      ConstantFactory<SparseBloomFilter> constantFactory0 = new ConstantFactory<SparseBloomFilter>(sparseBloomFilter0);
      LayerManager.Builder<SparseBloomFilter> layerManager_Builder1 = layerManager_Builder0.setSupplier(constantFactory0);
      LayerManager<SparseBloomFilter> layerManager0 = layerManager_Builder1.get();
      BloomFilter[] bloomFilterArray0 = layerManager0.asBloomFilterArray();
      assertEquals(1, bloomFilterArray0.length);
  }
}
