/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 01:39:47 GMT 2026
 */

package org.threeten.extra.chrono;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Clock;
import java.time.DateTimeException;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.chrono.ChronoZonedDateTime;
import java.time.chrono.Era;
import java.time.chrono.IsoEra;
import java.time.temporal.ChronoField;
import java.time.temporal.TemporalAccessor;
import java.time.temporal.TemporalAdjuster;
import java.time.temporal.ValueRange;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockOffsetDateTime;
import org.junit.runner.RunWith;
import org.threeten.extra.chrono.Symmetry454Chronology;
import org.threeten.extra.chrono.Symmetry454Date;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Symmetry454Chronology_ESTest extends Symmetry454Chronology_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.CLOCK_HOUR_OF_AMPM;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.YEAR;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.YEAR_OF_ERA;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.PROLEPTIC_MONTH;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.MONTH_OF_YEAR;
      ValueRange valueRange0 = symmetry454Chronology0.INSTANCE.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.ERA;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      ChronoField chronoField0 = ChronoField.DAY_OF_YEAR;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.DAY_OF_MONTH;
      ValueRange valueRange0 = symmetry454Chronology0.INSTANCE.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      ChronoField chronoField0 = ChronoField.ALIGNED_WEEK_OF_YEAR;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      ChronoField chronoField0 = ChronoField.ALIGNED_WEEK_OF_MONTH;
      ValueRange valueRange0 = symmetry454Chronology0.INSTANCE.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ChronoField chronoField0 = ChronoField.DAY_OF_WEEK;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      ChronoField chronoField0 = ChronoField.ALIGNED_DAY_OF_WEEK_IN_MONTH;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      Symmetry454Date symmetry454Date0 = symmetry454Chronology0.date(7, 1, 7);
      Symmetry454Date symmetry454Date1 = symmetry454Date0.with((TemporalAdjuster) symmetry454Date0);
      assertTrue(symmetry454Date1.equals((Object)symmetry454Date0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      ChronoField chronoField0 = ChronoField.ALIGNED_DAY_OF_WEEK_IN_YEAR;
      ValueRange valueRange0 = symmetry454Chronology0.range(chronoField0);
      assertNotNull(valueRange0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      // Undeclared exception!
      try { 
        symmetry454Chronology0.INSTANCE.eraOf(107016);
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid era: 107016
         //
         verifyException("java.time.chrono.IsoEra", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      String string0 = symmetry454Chronology0.getId();
      assertEquals("Sym454", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      // Undeclared exception!
      try { 
        symmetry454Chronology0.date((Era) null, (-2134851390), (-2134851390), (-2134851390));
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // Invalid era: null
         //
         verifyException("org.threeten.extra.chrono.Symmetry454Chronology", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds(0);
      Clock clock0 = MockClock.tickMinutes(zoneOffset0);
      Symmetry454Date symmetry454Date0 = Symmetry454Date.now(clock0);
      Symmetry454Chronology symmetry454Chronology0 = symmetry454Date0.getChronology();
      Symmetry454Date symmetry454Date1 = symmetry454Chronology0.dateNow(clock0);
      assertTrue(symmetry454Date1.equals((Object)symmetry454Date0));
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      IsoEra isoEra0 = IsoEra.BCE;
      // Undeclared exception!
      try { 
        symmetry454Chronology0.dateYearDay((Era) isoEra0, 4960, 4960);
        fail("Expecting exception: DateTimeException");
      
      } catch(DateTimeException e) {
         //
         // Invalid value for DayOfYear (valid values 1 - 364/371): 4960
         //
         verifyException("java.time.temporal.ValueRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      List<Era> list0 = symmetry454Chronology0.eras();
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      OffsetDateTime offsetDateTime0 = MockOffsetDateTime.now();
      ChronoZonedDateTime<Symmetry454Date> chronoZonedDateTime0 = symmetry454Chronology0.zonedDateTime((TemporalAccessor) offsetDateTime0);
      assertNotNull(chronoZonedDateTime0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      Symmetry454Date symmetry454Date0 = symmetry454Chronology0.dateNow();
      assertEquals(IsoEra.CE, symmetry454Date0.getEra());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      Symmetry454Date symmetry454Date0 = symmetry454Chronology0.dateEpochDay(1);
      assertEquals(IsoEra.CE, symmetry454Date0.getEra());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = Symmetry454Chronology.INSTANCE;
      String string0 = symmetry454Chronology0.getCalendarType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Symmetry454Chronology symmetry454Chronology0 = new Symmetry454Chronology();
      ZoneOffset zoneOffset0 = ZoneOffset.MAX;
      Symmetry454Date symmetry454Date0 = symmetry454Chronology0.INSTANCE.dateNow((ZoneId) zoneOffset0);
      assertEquals(IsoEra.CE, symmetry454Date0.getEra());
  }
}
