/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 16:05:04 GMT 2026
 */

package org.apache.commons.math4.legacy.ode.events;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.math4.legacy.analysis.solvers.IllinoisSolver;
import org.apache.commons.math4.legacy.analysis.solvers.MullerSolver;
import org.apache.commons.math4.legacy.analysis.solvers.PegasusSolver;
import org.apache.commons.math4.legacy.analysis.solvers.SecantSolver;
import org.apache.commons.math4.legacy.analysis.solvers.UnivariateSolver;
import org.apache.commons.math4.legacy.ode.ExpandableStatefulODE;
import org.apache.commons.math4.legacy.ode.FirstOrderConverter;
import org.apache.commons.math4.legacy.ode.SecondOrderDifferentialEquations;
import org.apache.commons.math4.legacy.ode.events.EventFilter;
import org.apache.commons.math4.legacy.ode.events.EventHandler;
import org.apache.commons.math4.legacy.ode.events.EventState;
import org.apache.commons.math4.legacy.ode.events.FilterType;
import org.apache.commons.math4.legacy.ode.sampling.NordsieckStepInterpolator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class EventState_ESTest extends EventState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-1.0), (-1.0));
      EventState eventState0 = new EventState(eventFilter0, 220.937034, 0.0, 1, illinoisSolver0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.reinitializeBegin(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.legacy.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState((EventHandler) null, 2145400828, 2145400828, 2145400828, mullerSolver0);
      boolean boolean0 = eventState0.reset(2145400828, (double[]) null);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertFalse(boolean0);
      assertEquals(2145400828, eventState0.getMaxIterationCount());
      assertEquals(2.145400828E9, eventState0.getMaxCheckInterval(), 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_DECREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      EventState eventState0 = new EventState(eventFilter0, 0.0, 0.0, 0, (UnivariateSolver) null);
      boolean boolean0 = eventState0.stop();
      assertEquals(0.0, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0, eventState0.getMaxIterationCount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState(eventHandler0, (-2146989590), (-2146989590), (-2146038312), mullerSolver0);
      double double0 = eventState0.getEventTime();
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
      assertEquals((-2146038312), eventState0.getMaxIterationCount());
      assertEquals((-2.14698959E9), eventState0.getMaxCheckInterval(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      doReturn((-1.2534241706168776E-8)).when(eventHandler0).g(anyDouble() , any(double[].class));
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState(eventHandler0, 2318, 2318, 2318, mullerSolver0);
      eventState0.stepAccepted(2318, (double[]) null);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      nordsieckStepInterpolator0.setSoftCurrentTime((-1.2534241706168776E-8));
      // Undeclared exception!
      try { 
        eventState0.evaluateStep(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.legacy.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      doReturn(0.0).when(eventHandler0).g(anyDouble() , any(double[].class));
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState(eventHandler0, (-2146989590), (-2146989590), (-2146038312), mullerSolver0);
      eventState0.stepAccepted((-2146038312), (double[]) null);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      nordsieckStepInterpolator0.setSoftCurrentTime((-2146989590));
      eventState0.evaluateStep(nordsieckStepInterpolator0);
      double double0 = eventState0.getEventTime();
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState(eventHandler0, 2318, 2318, 2318, mullerSolver0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.evaluateStep(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.math4.legacy.ode.events.EventState", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      MullerSolver mullerSolver0 = new MullerSolver();
      EventState eventState0 = new EventState(eventHandler0, 3, 3, 3, mullerSolver0);
      SecondOrderDifferentialEquations secondOrderDifferentialEquations0 = mock(SecondOrderDifferentialEquations.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(secondOrderDifferentialEquations0).getDimension();
      FirstOrderConverter firstOrderConverter0 = new FirstOrderConverter(secondOrderDifferentialEquations0);
      ExpandableStatefulODE expandableStatefulODE0 = new ExpandableStatefulODE(firstOrderConverter0);
      eventState0.setExpandable(expandableStatefulODE0);
      NordsieckStepInterpolator nordsieckStepInterpolator0 = new NordsieckStepInterpolator();
      // Undeclared exception!
      try { 
        eventState0.evaluateStep(nordsieckStepInterpolator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-1.0), (-1.0));
      EventState eventState0 = new EventState(eventFilter0, 220.937034, 0.0, 1, illinoisSolver0);
      int int0 = eventState0.getMaxIterationCount();
      assertEquals(0.0, eventState0.getConvergence(), 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(220.937034, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      IllinoisSolver illinoisSolver0 = new IllinoisSolver((-1.0), (-1.0));
      EventState eventState0 = new EventState(eventFilter0, 220.937034, 0.0, 1, illinoisSolver0);
      eventState0.getEventHandler();
      assertEquals(220.937034, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(1, eventState0.getMaxIterationCount());
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.0, eventState0.getConvergence(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      PegasusSolver pegasusSolver0 = new PegasusSolver(0, 0);
      EventState eventState0 = new EventState(eventFilter0, 2920.701917, 2920.701917, 0, pegasusSolver0);
      double double0 = eventState0.getConvergence();
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(2920.701917, double0, 0.01);
      assertEquals(2920.701917, eventState0.getMaxCheckInterval(), 0.01);
      assertEquals(0, eventState0.getMaxIterationCount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EventHandler eventHandler0 = mock(EventHandler.class, new ViolatedAssumptionAnswer());
      FilterType filterType0 = FilterType.TRIGGER_ONLY_INCREASING_EVENTS;
      EventFilter eventFilter0 = new EventFilter(eventHandler0, filterType0);
      SecantSolver secantSolver0 = new SecantSolver(0.0);
      EventState eventState0 = new EventState(eventFilter0, 0.0, 0.0, 1644, secantSolver0);
      double double0 = eventState0.getMaxCheckInterval();
      assertEquals(1644, eventState0.getMaxIterationCount());
      assertEquals(Double.NEGATIVE_INFINITY, eventState0.getEventTime(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }
}
