/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 04:27:54 GMT 2026
 */

package org.threeten.extra;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.CharBuffer;
import java.time.Clock;
import java.time.Instant;
import java.time.Period;
import java.time.chrono.HijrahDate;
import java.time.chrono.ThaiBuddhistDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoField;
import java.time.temporal.Temporal;
import java.time.temporal.TemporalAmount;
import java.time.temporal.TemporalUnit;
import java.time.temporal.UnsupportedTemporalTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockClock;
import org.evosuite.runtime.mock.java.time.MockInstant;
import org.evosuite.runtime.mock.java.time.chrono.MockHijrahDate;
import org.evosuite.runtime.mock.java.time.chrono.MockThaiBuddhistDate;
import org.junit.runner.RunWith;
import org.threeten.extra.Months;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Months_ESTest extends Months_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Months months0 = Months.of((-1428));
      Months months1 = months0.minus((-2443));
      boolean boolean0 = months1.equals(months0);
      assertFalse(months0.equals((Object)months1));
      assertEquals(1015, months1.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Months months0 = Months.of((-1428));
      Object object0 = new Object();
      boolean boolean0 = months0.equals(object0);
      assertEquals((-1428), months0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Months months0 = Months.ONE;
      boolean boolean0 = months0.equals(months0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Months months0 = Months.ONE;
      HijrahDate hijrahDate0 = MockHijrahDate.now();
      Temporal temporal0 = months0.subtractFrom(hijrahDate0);
      assertNotSame(temporal0, hijrahDate0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Months months0 = Months.ONE;
      Temporal temporal0 = months0.ZERO.subtractFrom((Temporal) null);
      assertNull(temporal0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Period period0 = Period.ofWeeks(0);
      Months months0 = Months.from(period0);
      Clock clock0 = MockClock.systemUTC();
      Instant instant0 = MockInstant.now(clock0);
      // Undeclared exception!
      try { 
        months0.ONE.addTo(instant0);
        fail("Expecting exception: UnsupportedTemporalTypeException");
      
      } catch(UnsupportedTemporalTypeException e) {
         //
         // Unsupported unit: Months
         //
         verifyException("java.time.Instant", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Months months0 = Months.ONE;
      Instant instant0 = MockInstant.now();
      Temporal temporal0 = months0.ZERO.addTo(instant0);
      assertSame(temporal0, instant0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.minus(2635);
      Months months2 = months1.abs();
      assertEquals((-2634), months1.getAmount());
      assertEquals(2634, months2.getAmount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.ONE.abs();
      assertTrue(months1.isPositive());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.ZERO.dividedBy(1);
      assertTrue(months1.isZero());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.dividedBy((-1271));
      assertTrue(months1.isZero());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.multipliedBy(1);
      assertEquals(1, months1.getAmount());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Months months0 = Months.ZERO;
      Months months1 = months0.minus((TemporalAmount) months0);
      assertSame(months1, months0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Months months0 = Months.ZERO;
      Months months1 = months0.ZERO.plus((TemporalAmount) months0);
      assertTrue(months1.isZero());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Months months0 = Months.ONE;
      boolean boolean0 = months0.isPositive();
      assertEquals(1, months0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Months months0 = Months.ONE;
      boolean boolean0 = months0.isZero();
      assertFalse(boolean0);
      assertEquals(1, months0.getAmount());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Months months0 = Months.ofYears((-2475));
      boolean boolean0 = months0.isNegative();
      assertTrue(boolean0);
      assertEquals((-29700), months0.getAmount());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Months months0 = Months.ONE;
      boolean boolean0 = months0.isNegative();
      assertFalse(boolean0);
      assertEquals(1, months0.getAmount());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Months months0 = Months.ONE;
      ChronoField chronoField0 = ChronoField.ALIGNED_WEEK_OF_MONTH;
      TemporalUnit temporalUnit0 = chronoField0.getBaseUnit();
      // Undeclared exception!
      try { 
        months0.get(temporalUnit0);
        fail("Expecting exception: UnsupportedTemporalTypeException");
      
      } catch(UnsupportedTemporalTypeException e) {
         //
         // Unsupported unit: Weeks
         //
         verifyException("org.threeten.extra.Months", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(419);
      // Undeclared exception!
      try { 
        Months.parse(charBuffer0);
        fail("Expecting exception: DateTimeParseException");
      
      } catch(DateTimeParseException e) {
         //
         // Text cannot be parsed to a Months
         //
         verifyException("org.threeten.extra.Months", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Period period0 = Period.ofYears(0);
      Period period1 = period0.minusMonths((-1L));
      Months months0 = Months.from(period1);
      assertEquals(1, months0.getAmount());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Months months0 = Months.ofYears(0);
      boolean boolean0 = months0.isZero();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Months months0 = Months.ofYears(83);
      Period period0 = Period.from(months0);
      Months months1 = Months.from(period0);
      boolean boolean0 = months0.equals(months1);
      assertEquals(996, months0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Months months0 = Months.ONE;
      String string0 = months0.toString();
      assertEquals("P1M", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Months months0 = Months.ONE;
      Period period0 = months0.toPeriod();
      assertNotNull(period0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.ZERO.plus((TemporalAmount) months0);
      assertSame(months1, months0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Months months0 = Months.ONE;
      months0.hashCode();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Months months0 = Months.ONE;
      Months months1 = months0.minus((TemporalAmount) months0);
      boolean boolean0 = months1.isPositive();
      assertTrue(months0.isPositive());
      assertEquals(0, months1.getAmount());
      assertEquals(1, months0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ThaiBuddhistDate thaiBuddhistDate0 = MockThaiBuddhistDate.now();
      Months months0 = Months.between(thaiBuddhistDate0, thaiBuddhistDate0);
      assertTrue(months0.isZero());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Months months0 = Months.ONE;
      int int0 = months0.compareTo(months0);
      assertEquals(0, int0);
  }
}
