/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jun 16 03:08:54 GMT 2026
 */

package org.threeten.extra;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MutableClock_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.threeten.extra.MutableClock"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/tenghaha/Projects/New_Agent_understandability_improvement/scripts"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/y7/5v6zwzln5s14jn6cndl4lq7m0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MutableClock_ESTest_scaffolding.class.getClassLoader() ,
      "org.threeten.extra.MutableClock",
      "org.threeten.extra.MutableClock$InstantHolder"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MutableClock_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.threeten.extra.MutableClock",
      "org.threeten.extra.MutableClock$InstantHolder",
      "org.threeten.extra.MutableClock$SerializationProxy",
      "org.threeten.extra.chrono.BritishCutoverChronology",
      "org.threeten.extra.chrono.AbstractNileChronology",
      "org.threeten.extra.chrono.CopticChronology",
      "org.threeten.extra.chrono.DiscordianChronology",
      "org.threeten.extra.chrono.EthiopicChronology",
      "org.threeten.extra.chrono.InternationalFixedChronology",
      "org.threeten.extra.chrono.JulianChronology",
      "org.threeten.extra.chrono.PaxChronology",
      "org.threeten.extra.chrono.Symmetry010Chronology",
      "org.threeten.extra.chrono.Symmetry454Chronology",
      "org.threeten.extra.chrono.InternationalFixedEra",
      "org.threeten.extra.chrono.AbstractDate",
      "org.threeten.extra.chrono.BritishCutoverDate",
      "org.threeten.extra.chrono.JulianDate",
      "org.threeten.extra.chrono.JulianChronology$1",
      "org.threeten.extra.chrono.AbstractDate$1",
      "org.threeten.extra.chrono.AbstractNileDate",
      "org.threeten.extra.chrono.CopticDate",
      "org.threeten.extra.chrono.PaxDate",
      "org.threeten.extra.chrono.Symmetry454Date",
      "org.threeten.extra.chrono.JulianEra"
    );
  }
}
