/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 17 06:01:47 GMT 2026
 */

package org.apache.commons.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.Writer;
import java.nio.CharBuffer;
import java.util.HashMap;
import org.apache.commons.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMap<CharSequence, CharSequence> hashMap0 = new HashMap<CharSequence, CharSequence>(2572, 2572);
      CharBuffer charBuffer0 = CharBuffer.allocate(2572);
      hashMap0.put(charBuffer0, charBuffer0);
      char[] charArray0 = new char[6];
      CharBuffer charBuffer1 = CharBuffer.wrap(charArray0);
      hashMap0.put(charBuffer1, charBuffer0);
      Writer writer0 = Writer.nullWriter();
      LookupTranslator lookupTranslator0 = new LookupTranslator(hashMap0);
      int int0 = lookupTranslator0.translate((CharSequence) charBuffer0, 1587, writer0);
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashMap<CharSequence, CharSequence> hashMap0 = new HashMap<CharSequence, CharSequence>(2572, 2572);
      CharBuffer charBuffer0 = CharBuffer.allocate(2572);
      hashMap0.put(charBuffer0, charBuffer0);
      LookupTranslator lookupTranslator0 = new LookupTranslator(hashMap0);
      Writer writer0 = Writer.nullWriter();
      int int0 = lookupTranslator0.translate((CharSequence) charBuffer0, 1587, writer0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HashMap<CharSequence, CharSequence> hashMap0 = new HashMap<CharSequence, CharSequence>();
      LookupTranslator lookupTranslator0 = new LookupTranslator(hashMap0);
      CharBuffer charBuffer0 = CharBuffer.allocate(2570);
      String string0 = lookupTranslator0.translate((CharSequence) charBuffer0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashMap<CharSequence, CharSequence> hashMap0 = new HashMap<CharSequence, CharSequence>(2572, 2572);
      CharBuffer charBuffer0 = CharBuffer.allocate(2572);
      hashMap0.put(charBuffer0, charBuffer0);
      LookupTranslator lookupTranslator0 = new LookupTranslator(hashMap0);
      String string0 = lookupTranslator0.translate((CharSequence) charBuffer0);
      hashMap0.put(string0, charBuffer0);
      LookupTranslator lookupTranslator1 = new LookupTranslator(hashMap0);
      assertFalse(lookupTranslator1.equals((Object)lookupTranslator0));
  }
}
