/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 15 08:44:51 GMT 2026
 */

package org.apache.commons.compress.harmony.pack200;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.EOFException;
import java.io.InputStream;
import org.apache.commons.compress.harmony.pack200.BHSDCodec;
import org.apache.commons.compress.harmony.pack200.Codec;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Codec_ESTest extends Codec_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BHSDCodec bHSDCodec0 = Codec.DELTA5;
      byte[] byteArray0 = new byte[7];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (byte) (-46), 1452);
      // Undeclared exception!
      try { 
        bHSDCodec0.decodeInts(5, (InputStream) byteArrayInputStream0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BHSDCodec bHSDCodec0 = Codec.BCI5;
      int[] intArray0 = new int[2];
      byte[] byteArray0 = bHSDCodec0.encode(intArray0);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 0, 0);
      try { 
        bHSDCodec0.decodeInts(22, (InputStream) byteArrayInputStream0, 22);
        fail("Expecting exception: EOFException");
      
      } catch(EOFException e) {
         //
         // End of stream reached whilst decoding
         //
         verifyException("org.apache.commons.compress.harmony.pack200.BHSDCodec", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BHSDCodec bHSDCodec0 = Codec.DELTA5;
      int[] intArray0 = new int[14];
      byte[] byteArray0 = bHSDCodec0.encode(intArray0);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 0, 0);
      int[] intArray1 = bHSDCodec0.decodeInts(0, (InputStream) byteArrayInputStream0);
      assertEquals(0, intArray1.length);
      assertEquals(14, byteArray0.length);
      assertEquals(0, bHSDCodec0.lastBandLength);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BHSDCodec bHSDCodec0 = Codec.UNSIGNED5;
      int[] intArray0 = new int[1];
      byte[] byteArray0 = bHSDCodec0.encode(intArray0);
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 0, 60);
      int[] intArray1 = bHSDCodec0.decodeInts(0, (InputStream) byteArrayInputStream0, 1442);
      assertEquals(1, byteArray0.length);
      assertArrayEquals(new int[] {1442}, intArray1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BHSDCodec bHSDCodec0 = null;
      try {
        bHSDCodec0 = new BHSDCodec(11, 0, 60);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 1<=b<=5
         //
         verifyException("org.apache.commons.compress.harmony.pack200.BHSDCodec", e);
      }
  }
}
