/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 16 07:22:21 GMT 2026
 */

package com.itextpdf.text.error_messages;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.itextpdf.text.error_messages.MessageLocalization;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class MessageLocalization_ESTest extends MessageLocalization_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringReader stringReader0 = new StringReader("#/#9w{NsI8\u0000gV=2_");
      MessageLocalization.setMessages(stringReader0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = MessageLocalization.setLanguage("@nNphh", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = MessageLocalization.setLanguage("en", (String) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageLocalization.setLanguage((String) null, "e6C(");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The language cannot be null.
         //
         verifyException("com.itextpdf.text.error_messages.MessageLocalization", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      boolean boolean0 = MessageLocalization.setLanguage(".lng", ".lng");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = MessageLocalization.getComposedMessage("x", (Object[]) null);
      assertNotNull(string0);
      assertEquals("No message found for x", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = MessageLocalization.getMessage("verification.already.output", true);
      assertEquals("Verification already output", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = MessageLocalization.getMessage("iqp1QFh}R4Yj$j:Q", false);
      assertEquals("No message found for iqp1QFh}R4Yj$j:Q", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      String string0 = MessageLocalization.getComposedMessage((String) null, 1245);
      assertEquals("No message found for null", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      boolean boolean0 = MessageLocalization.setLanguage("en", "en");
      assertTrue(boolean0);
      
      String string0 = MessageLocalization.getComposedMessage((String) null, 1245);
      assertNotNull(string0);
      assertEquals("No message found for null", string0);
  }
}
