package org.apache.commons.io.input;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;

import org.junit.jupiter.api.Test;

public class NullInputStreamTest_testMarkAndReset {

    /**
     * A {@link NullInputStream} whose generated byte at any position equals that
     * position index (0, 1, 2, ...), so a {@code read()} at position {@code p}
     * returns {@code p}. This makes the effect of mark/reset on the stream
     * position directly observable through the returned byte values.
     */
    private static final class TestNullInputStream extends NullInputStream {

        TestNullInputStream(final int size) {
            super(size);
        }

        TestNullInputStream(final int size, final boolean markSupported, final boolean throwEofException) {
            super(size, markSupported, throwEofException);
        }

        @Override
        protected int processByte() {
            return (int) getPosition() - 1;
        }

        @Override
        protected void processBytes(final byte[] bytes, final int offset, final int length) {
            final int startPos = (int) getPosition() - length;
            for (int i = offset; i < length; i++) {
                bytes[i] = (byte) (startPos + i);
            }
        }
    }

    @Test
    void testMarkAndReset() throws Exception {
        final int streamSize = 100;
        final int readLimit = 10;

        try (InputStream input = new TestNullInputStream(streamSize, true, false)) {
            assertTrue(input.markSupported(), "Mark Should be Supported");

            // reset() before any mark() must fail.
            final IOException noMarkException = assertThrows(IOException.class, input::reset);
            assertEquals("No position has been marked", noMarkException.getMessage(), "No Mark IOException message");

            // Read the first 3 bytes (positions 0, 1, 2); each read returns its own position.
            final int markPosition = 3;
            for (int position = 0; position < markPosition; position++) {
                assertEquals(position, input.read(), "Read Before Mark [" + position + "]");
            }

            // Mark the current position (3), allowing up to readLimit bytes before it becomes invalid.
            input.mark(readLimit);

            // Read 3 more bytes past the mark (positions 3, 4, 5).
            for (int offsetFromMark = 0; offsetFromMark < 3; offsetFromMark++) {
                assertEquals(markPosition + offsetFromMark, input.read(), "Read After Mark [" + offsetFromMark + "]");
            }

            // Reset back to the marked position (3).
            input.reset();

            // Re-read from the marked position. Reading readLimit + 1 bytes advances the
            // position just past mark + readLimit, which invalidates the mark.
            for (int offsetFromMark = 0; offsetFromMark < readLimit + 1; offsetFromMark++) {
                assertEquals(markPosition + offsetFromMark, input.read(), "Read After Reset [" + offsetFromMark + "]");
            }

            // The read limit has now been exceeded, so reset() must fail.
            final IOException resetException = assertThrows(IOException.class, input::reset, "Read limit exceeded, expected IOException");
            assertEquals("Marked position [" + markPosition + "] is no longer valid - passed the read limit [" + readLimit + "]",
                    resetException.getMessage(), "Read limit IOException message");
        }
    }
}
